# Generated by Django 5.2.5 on 2025-10-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobRequisitions', '0002_request_cancelled_by_details_request_cancelled_by_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='requested_by_details',
            field=models.JSONField(blank=True, default=dict, help_text='Details of the user who requested the request', null=True),
        ),
    ]
