# Generated by Django 5.2.5 on 2025-10-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobRequisitions', '0003_request_requested_by_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequisition',
            name='approved_by_details',
            field=models.JSONField(blank=True, default=dict, help_text='Details of approver from JWT'),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='branch_name',
            field=models.CharField(blank=True, help_text='Branch name fetched once at create', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='created_by_details',
            field=models.JSONField(blank=True, default=dict, help_text='Details of creator from JWT'),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='requested_by_details',
            field=models.JSONField(blank=True, default=dict, help_text='Details of requester from JWT'),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='tenant_domain',
            field=models.CharField(blank=True, help_text='Tenant domain from JWT', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='updated_by_details',
            field=models.JSONField(blank=True, default=dict, help_text='Details of last updater from JWT'),
        ),
    ]
