# Generated by Django 5.2.5 on 2025-10-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobRequisitions', '0004_jobrequisition_approved_by_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrequisition',
            name='branch_id',
        ),
        migrations.RemoveField(
            model_name='jobrequisition',
            name='branch_name',
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='tenant_schema',
            field=models.CharField(blank=True, help_text='Tenant schema from JWT for code prefix', max_length=255, null=True),
        ),
    ]
