# Generated by Django 4.2.25 on 2025-10-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_penalties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalty',
            name='issuing_authority',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='issuing_authority',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='type',
            field=models.CharField(choices=[('bonus', 'BONUS'), ('promotion', 'PROMOTION'), ('recognition', 'RECOGNITION'), ('extra_pto', 'EXTRA_PTO'), ('gift', 'GIFT'), ('public_praise', 'PUBLIC_PRAISE'), ('certificate', 'CERTIFICATE'), ('training_opportunity', 'TRAINING_OPPORTUNITY'), ('other', 'OTHER')], default='bonus', max_length=50),
        ),
    ]
