# Generated by Django 4.2.25 on 2025-10-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_penalties', '0002_penalty_issuing_authority_reward_issuing_authority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penalty',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='employee_id',
        ),
        migrations.AlterField(
            model_name='reward',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
