services:
  api_gateway:
    build: .
    container_name: api_gateway
    ports:
      - "9090:9090"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
    networks:
      - auth_service_default

networks:
  auth_service_default:
    external: true
