
services:
  api_gateway:
    build: .
    ports:
      - "9091:9090"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
    networks:
      - auth_service_default

networks:
  auth_service_default:
    external: true


