# Generated by Django 5.2.2 on 2025-08-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_scormtracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('scorm', 'SCORM')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='scorm_launch_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='scorm_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
