# Generated by Django 5.2.5 on 2025-11-24 17:12

import django.db.models.deletion
import knowledge_base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(default=knowledge_base.models.gen_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.CharField(default=knowledge_base.models.gen_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(default='default-tenant', max_length=255)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.CharField(default=knowledge_base.models.gen_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(default='default-tenant', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True, help_text='Short summary of the article')),
                ('author_id', models.CharField(max_length=128)),
                ('author_first_name', models.CharField(max_length=150)),
                ('author_last_name', models.CharField(max_length=150)),
                ('author_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('featured_image', models.URLField(blank=True, help_text='URL to featured image')),
                ('reading_time', models.PositiveIntegerField(default=0, help_text='Estimated reading time in minutes')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='knowledge_base.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='knowledge_base.tag')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
