[
  {
    "email": "john.doe@example.com",
    "password": "SecurePass123!",
    "first_name": "John",
    "last_name": "Doe",
    "role": "carer",
    "job_role": "Senior Care Assistant",
    "has_accepted_terms": true,
    
    "profile": {
      "salary_rate": "hourly",
      "availability": {
        "monday": {"available": true, "start": "09:00", "end": "17:00"},
        "tuesday": {"available": true, "start": "09:00", "end": "17:00"},
        "wednesday": {"available": true, "start": "09:00", "end": "17:00"},
        "thursday": {"available": true, "start": "09:00", "end": "17:00"},
        "friday": {"available": true, "start": "09:00", "end": "17:00"},
        "saturday": {"available": false},
        "sunday": {"available": false}
      },
      "work_phone": "+1234567890",
      "personal_phone": "+1234567891",
      "gender": "Male",
      "dob": "1990-05-15",
      "street": "123 Main Street",
      "city": "London",
      "state": "Greater London",
      "country": "United Kingdom",
      "zip_code": "SW1A 1AA",
      "department": "Healthcare",
      "marital_status": "Single",
      "is_driver": true,
      "type_of_vehicle": "Personal Vehicle",
      "drivers_licence_country_of_issue": "United Kingdom",
      "drivers_licence_date_issue": "2015-06-01",
      "drivers_licence_expiry_date": "2025-06-01",
      "drivers_license_insurance_provider": "ABC Insurance",
      "drivers_licence_insurance_expiry_date": "2024-12-31",
      "drivers_licence_issuing_authority": "DVLA",
      "drivers_licence_policy_number": "POL123456",
      "assessor_name": "Dr. Smith",
      "manual_handling_risk": "Low",
      "lone_working_risk": "Low",
      "infection_risk": "Low",
      "next_of_kin": "Jane Doe",
      "next_of_kin_address": "456 Oak Avenue",
      "next_of_kin_phone_number": "+1234567892",
      "next_of_kin_alternate_phone": "+1234567893",
      "relationship_to_next_of_kin": "Sister",
      "next_of_kin_email": "jane.doe@example.com",
      "next_of_kin_town": "Manchester",
      "next_of_kin_zip_code": "M1 1AA",
      "Right_to_Work_status": "Permanent",
      "Right_to_Work_passport_holder": "British",
      "Right_to_Work_document_type": "Passport",
      "Right_to_Work_document_number": "123456789",
      "Right_to_Work_document_expiry_date": "2030-12-31",
      "Right_to_Work_country_of_issue": "United Kingdom",
      "Right_to_Work_restrictions": "None",
      "dbs_type": "Enhanced",
      "dbs_certificate_number": "DBS123456789",
      "dbs_issue_date": "2023-01-15",
      "dbs_update_certificate_number": "UPD987654321",
      "dbs_update_issue_date": "2024-01-15",
      "dbs_status_check": true,
      "bank_name": "Barclays Bank",
      "account_number": "12345678",
      "account_name": "John Doe",
      "account_type": "Current",
      "country_of_bank_account": "UK",
      "sort_code": "20-00-00",
      "iban": "GB29NWBK60161331926819",
      "bic_swift": "BARCGB22",
      "national_insurance_number": "AB123456C",
      "consent_given": true,
      "system_access_rostering": true,
      "system_access_hr": false,
      "system_access_recruitment": false,
      "system_access_training": true,
      "system_access_finance": false,
      "system_access_compliance": true,
  }
  },
  {
    "email": "sarah.smith@example.com",
    "password": "SecurePass456!",
    "first_name": "Sarah",
    "last_name": "Smith",
    "role": "hr",
    "job_role": "HR Manager",
    "has_accepted_terms": true,
    "permission_levels": ["view_dashboard", "manage_users", "manage_hr"],
    "profile": {
      "salary_rate": "monthly",
      "availability": {
        "monday": {"available": true, "start": "08:00", "end": "16:00"},
        "tuesday": {"available": true, "start": "08:00", "end": "16:00"},
        "wednesday": {"available": true, "start": "08:00", "end": "16:00"},
        "thursday": {"available": true, "start": "08:00", "end": "16:00"},
        "friday": {"available": true, "start": "08:00", "end": "16:00"},
        "saturday": {"available": false},
        "sunday": {"available": false}
      },
      "work_phone": "+1234567895",
      "personal_phone": "+1234567896",
      "gender": "Female",
      "dob": "1985-08-22",
      "street": "789 Park Lane",
      "city": "Birmingham",
      "state": "West Midlands",
      "country": "United Kingdom",
      "zip_code": "B1 1AA",
      "department": "Human Resources",
      "marital_status": "Married",
      "is_driver": false,
      "next_of_kin": "Michael Smith",
      "next_of_kin_phone_number": "+1234567897",
      "relationship_to_next_of_kin": "Husband",
      "next_of_kin_email": "michael.smith@example.com",
      "Right_to_Work_status": "Permanent",
      "Right_to_Work_document_type": "Passport",
      "Right_to_Work_document_number": "987654321",
      "Right_to_Work_document_expiry_date": "2029-05-20",
      "Right_to_Work_country_of_issue": "United Kingdom",
      "bank_name": "HSBC",
      "account_number": "87654321",
      "account_name": "Sarah Smith",
      "account_type": "Current",
      "country_of_bank_account": "UK",
      "sort_code": "40-00-00",
      "consent_given": true,
      "system_access_hr": true,
      "system_access_recruitment": true,
      "system_access_compliance": true,
 }
  },
  {
    "email": "investor.jones@example.com",
    "password": "InvestPass789!",
    "first_name": "Robert",
    "last_name": "Jones",
    "role": "investor",
    "job_role": "Investment Partner",
    "profile": {
      "work_phone": "+1234567898",
      "personal_phone": "+1234567899",
      "gender": "Male",
      "dob": "1975-03-10",
      "street": "321 Investment Avenue",
      "city": "Leeds",
      "state": "West Yorkshire",
      "country": "United Kingdom",
      "zip_code": "LS1 1AA",
      "marital_status": "Married",
      "bank_name": "Lloyds Bank",
      "account_number": "11223344",
      "account_name": "Robert Jones",
      "account_type": "Business",
      "country_of_bank_account": "UK",
      "sort_code": "30-00-00",
      "consent_given": true,
    }
  },
  {
    "email": "team.leader@example.com",
    "password": "TeamPass321!",
    "first_name": "Emma",
    "last_name": "Williams",
    "role": "team_manager",
    "job_role": "Team Leader",
    "has_accepted_terms": true,
    "profile": {
      "salary_rate": "annual",
      "availability": {
        "monday": {"available": true, "start": "07:00", "end": "19:00"},
        "tuesday": {"available": true, "start": "07:00", "end": "19:00"},
        "wednesday": {"available": true, "start": "07:00", "end": "19:00"},
        "thursday": {"available": true, "start": "07:00", "end": "19:00"},
        "friday": {"available": true, "start": "07:00", "end": "15:00"},
        "saturday": {"available": true, "start": "09:00", "end": "13:00"},
        "sunday": {"available": false}
      },
      "work_phone": "+1234567900",
      "personal_phone": "+1234567901",
      "gender": "Female",
      "dob": "1988-11-30",
      "street": "567 Leadership Road",
      "city": "Liverpool",
      "state": "Merseyside",
      "country": "United Kingdom",
      "zip_code": "L1 1AA",
      "department": "Operations",
      "marital_status": "Single",
      "is_driver": true,
      "type_of_vehicle": "Company Vehicle",
      "drivers_licence_country_of_issue": "United Kingdom",
      "drivers_licence_date_issue": "2010-03-15",
      "drivers_licence_expiry_date": "2030-03-15",
      "bank_name": "NatWest",
      "account_number": "55667788",
      "account_name": "Emma Williams",
      "account_type": "Current",
      "country_of_bank_account": "UK",
      "sort_code": "60-00-00",
      "consent_given": true,
      "system_access_rostering": true,
      "system_access_training": true,
    }
  },
  {
    "email": "recruiter.brown@example.com",
    "password": "RecruitPass654!",
    "first_name": "David",
    "last_name": "Brown",
    "role": "recruiter",
    "job_role": "Senior Recruiter",
    
    "profile": {
      "salary_rate": "monthly",
      "work_phone": "+1234567902",
      "personal_phone": "+1234567903",
      "gender": "Male",
      "dob": "1992-07-18",
      "street": "890 Talent Street",
      "city": "Bristol",
      "state": "South West",
      "country": "United Kingdom",
      "zip_code": "BS1 1AA",
      "department": "Recruitment",
      "marital_status": "Single",
      "bank_name": "Santander",
      "account_number": "99887766",
      "account_name": "David Brown",
      "account_type": "Current",
      "country_of_bank_account": "UK",
      "sort_code": "09-01-28",
      "consent_given": true,
      "system_access_recruitment": true,
      "system_access_hr": true,
    
    }
  }
]