
[
  
  
  {
    "email": "qwertyrickon.stark@example.com",
    "password": "StrongPass456$",
    "first_name": "Rickon",
    "last_name": "Stark",
    "role": "investor",
    "job_role": "Project Manager",
    "has_accepted_terms": true,
    "permission_levels": [
      "read",
      "write",
      "approve"
    ],
    "profile": {
      "work_phone": "+44-7700-900221",
      "personal_phone": "+44-7700-900222",
      "gender": "Male",
      "dob": "1989-11-03",
      "street": "88 River Lane",
      "city": "Birmingham",
      "state": "West Midlands",
      "zip_code": "B1 1AA",
      "marital_status": "Married",
      "next_of_kin": "Laura Brown",
      "next_of_kin_phone_number": "+44-7700-900223",
      "relationship_to_next_of_kin": "Wife",
      "next_of_kin_email": "laura.brown@example.com",
      "Right_to_Work_document_number": "UKRP445566",
      "Right_to_Work_document_expiry_date": "2030-07-10",
      "dbs_type": "Enhanced",
      "dbs_certificate_number": "DBS333444",
      "dbs_issue_date": "2025-01-17",
      "bank_name": "Lloyds Bank",
      "account_number": "3333444455",
      "account_name": "Rickon Stark",
      "account_type": "Savings",
      "is_driver": true
    }
  },
  {
    "email": "qwertyjon.snow@example.com",
    "password": "StrongPass456$",
    "first_name": "Jon",
    "last_name": "Snow",
    "role": "investor",
    "job_role": "Project Manager",
    "has_accepted_terms": true,
    "permission_levels": [
      "read",
      "write",
      "approve"
    ],
    "profile": {
      "work_phone": "+44-7700-900331",
      "personal_phone": "+44-7700-900332",
      "gender": "Female",
      "dob": "1994-04-08",
      "street": "29 King Street",
      "city": "Leeds",
      "state": "West Yorkshire",
      "zip_code": "LS1 4AA",
      "marital_status": "Single",
      "next_of_kin": "Michael Smith",
      "next_of_kin_phone_number": "+44-7700-900333",
      "relationship_to_next_of_kin": "Brother",
      "next_of_kin_email": "michael.smith@example.com",
      "Right_to_Work_document_number": "UKRP778899",
      "Right_to_Work_document_expiry_date": "2033-03-12",
      "dbs_type": "Basic",
      "dbs_certificate_number": "DBS555666",
      "dbs_issue_date": "2023-11-22",
      "bank_name": "NatWest Bank",
      "account_number": "5555666677",
      "account_name": "Jon Snow",
      "account_type": "Current",
      "is_driver": false
    }
  },
  {
    "email": "qwertybenjen.stark@example.com",
    "password": "StrongPass456$",
    "first_name": "Benjen",
    "last_name": "Stark",
    "role": "investor",
    "job_role": "Project Manager",
    "has_accepted_terms": true,
    "permission_levels": [
      "read",
      "write",
      "approve"
    ],
    "profile": {
      "work_phone": "+44-7700-900441",
      "personal_phone": "+44-7700-900442",
      "gender": "Male",
      "dob": "1992-07-20",
      "street": "10 Bridge Road",
      "city": "Liverpool",
      "state": "Merseyside",
      "zip_code": "L1 8AA",
      "marital_status": "Married",
      "next_of_kin": "Emma Thompson",
      "next_of_kin_phone_number": "+44-7700-900443",
      "relationship_to_next_of_kin": "Wife",
      "next_of_kin_email": "emma.thompson@example.com",
      "Right_to_Work_document_number": "UKRP990011",
      "Right_to_Work_document_expiry_date": "2031-01-25",
      "dbs_type": "Standard",
      "dbs_certificate_number": "DBS777888",
      "dbs_issue_date": "2024-10-01",
      "bank_name": "Santander Bank",
      "account_number": "7777888899",
      "account_name": "Benjen Stark",
      "account_type": "Savings",
      "is_driver": true
    }
  },
  {
    "email": "qwertyrobert.baratheon@example.com",
    "password": "StrongPass456$",
    "first_name": "Robert",
    "last_name": "Baratheon",
    "role": "investor",
    "job_role": "Project Manager",
    "has_accepted_terms": true,
    "permission_levels": [
      "read",
      "write",
      "approve"
    ],
    "profile": {
      "work_phone": "+44-7700-900551",
      "personal_phone": "+44-7700-900552",
      "gender": "Female",
      "dob": "1996-12-05",
      "street": "7 Maple Close",
      "city": "Bristol",
      "state": "Avon",
      "zip_code": "BS1 3AA",
      "marital_status": "Single",
      "next_of_kin": "Anna Miller",
      "next_of_kin_phone_number": "+44-7700-900553",
      "relationship_to_next_of_kin": "Mother",
      "next_of_kin_email": "anna.miller@example.com",
      "Right_to_Work_document_number": "UKRP223344",
      "Right_to_Work_document_expiry_date": "2034-09-09",
      "dbs_type": "Enhanced",
      "dbs_certificate_number": "DBS999000",
      "dbs_issue_date": "2025-02-15",
      "bank_name": "Monzo Bank",
      "account_number": "9999000011",
      "account_name": "Robert Baratheon",
      "account_type": "Current",
      "is_driver": false
    }
  },
  {
    "email": "qwertystannis.baratheon@example.com",
    "password": "StrongPass456$",
    "first_name": "Stannis",
    "last_name": "Baratheon",
    "role": "investor",
    "job_role": "Project Manager",
    "has_accepted_terms": true,
    "permission_levels": [
      "read",
      "write",
      "approve"
    ],
    "profile": {
      "work_phone": "+44-7700-900111",
      "personal_phone": "+44-7700-900112",
      "gender": "Female",
      "dob": "1991-02-14",
      "street": "15 Oak Avenue",
      "city": "Manchester",
      "state": "Greater Manchester",
      "zip_code": "M1 2AB",
      "marital_status": "Single",
      "next_of_kin": "Sarah Watson",
      "next_of_kin_phone_number": "+44-7700-900113",
      "relationship_to_next_of_kin": "Sister",
      "next_of_kin_email": "sarah.watson@example.com",
      "Right_to_Work_document_number": "UKRP112233",
      "Right_to_Work_document_expiry_date": "2031-09-22",
      "dbs_type": "Standard",
      "dbs_certificate_number": "DBS111222",
      "dbs_issue_date": "2024-03-05",
      "bank_name": "HSBC Bank",
      "account_number": "1111222233",
      "account_name": "Stannis Baratheon",
      "account_type": "Current",
      "is_driver": false
    }
  },
  {
    "email": "qwertyrenly.baratheon@example.com",
    "password": "StrongPass456$",
    "first_name": "Renly",
    "last_name": "Baratheon",
    "role": "investor",
    "job_role": "Project Manager",
    "has_accepted_terms": true,
    "permission_levels": [
      "read",
      "write",
      "approve"
    ],
    "profile": {
      "work_phone": "+44-7700-900221",
      "personal_phone": "+44-7700-900222",
      "gender": "Male",
      "dob": "1989-11-03",
      "street": "88 River Lane",
      "city": "Birmingham",
      "state": "West Midlands",
      "zip_code": "B1 1AA",
      "marital_status": "Married",
      "next_of_kin": "Laura Brown",
      "next_of_kin_phone_number": "+44-7700-900223",
      "relationship_to_next_of_kin": "Wife",
      "next_of_kin_email": "laura.brown@example.com",
      "Right_to_Work_document_number": "UKRP445566",
      "Right_to_Work_document_expiry_date": "2030-07-10",
      "dbs_type": "Enhanced",
      "dbs_certificate_number": "DBS333444",
      "dbs_issue_date": "2025-01-17",
      "bank_name": "Lloyds Bank",
      "account_number": "3333444455",
      "account_name": "Renly Baratheon",
      "account_type": "Savings",
      "is_driver": true
    }
  },
  
]

[ 
  {
    "email": "qwertyjoffrey.baratheon@example.com",
    "password": "StrongPass456$",
    "first_name": "Joffrey",
    "last_name": "Baratheon",
    "role": "investor",
    "job_role": "Project Manager",
    "has_accepted_terms": true,
    "permission_levels": [
      "read",
      "write",
      "approve"
    ],
    "profile": {
      "work_phone": "+44-7700-900331",
      "personal_phone": "+44-7700-900332",
      "gender": "Female",
      "dob": "1994-04-08",
      "street": "29 King Street",
      "city": "Leeds",
      "state": "West Yorkshire",
      "zip_code": "LS1 4AA",
      "marital_status": "Single",
      "next_of_kin": "Michael Smith",
      "next_of_kin_phone_number": "+44-7700-900333",
      "relationship_to_next_of_kin": "Brother",
      "next_of_kin_email": "michael.smith@example.com",
      "Right_to_Work_document_number": "UKRP778899",
      "Right_to_Work_document_expiry_date": "2033-03-12",
      "dbs_type": "Basic",
      "dbs_certificate_number": "DBS555666",
      "dbs_issue_date": "2023-11-22",
      "bank_name": "NatWest Bank",
      "account_number": "5555666677",
      "account_name": "Joffrey Baratheon",
      "account_type": "Current",
      "is_driver": false
    }
  },
  {
    "email": "qwertymyrcella.baratheon@example.com",
    "password": "StrongPass456$",
    "first_name": "Myrcella",
    "last_name": "Baratheon",
    "role": "investor",
    "job_role": "Project Manager",
    "has_accepted_terms": true,
    "permission_levels": [
      "read",
      "write",
      "approve"
    ],
    "profile": {
      "work_phone": "+44-7700-900441",
      "personal_phone": "+44-7700-900442",
      "gender": "Male",
      "dob": "1992-07-20",
      "street": "10 Bridge Road",
      "city": "Liverpool",
      "state": "Merseyside",
      "zip_code": "L1 8AA",
      "marital_status": "Married",
      "next_of_kin": "Emma Thompson",
      "next_of_kin_phone_number": "+44-7700-900443",
      "relationship_to_next_of_kin": "Wife",
      "next_of_kin_email": "emma.thompson@example.com",
      "Right_to_Work_document_number": "UKRP990011",
      "Right_to_Work_document_expiry_date": "2031-01-25",
      "dbs_type": "Standard",
      "dbs_certificate_number": "DBS777888",
      "dbs_issue_date": "2024-10-01",
      "bank_name": "Santander Bank",
      "account_number": "7777888899",
      "account_name": "Myrcella Baratheon",
      "account_type": "Savings",
      "is_driver": true
    }
  },
  {
    "email": "qwertythomas.baratheon@example.com",
    "password": "StrongPass456$",
    "first_name": "Tommen",
    "last_name": "Baratheon",
    "role": "investor",
    "job_role": "Project Manager",
    "has_accepted_terms": true,
    "permission_levels": [
      "read",
      "write",
      "approve"
    ],
    "profile": {
      "work_phone": "+44-7700-900551",
      "personal_phone": "+44-7700-900552",
      "gender": "Female",
      "dob": "1996-12-05",
      "street": "7 Maple Close",
      "city": "Bristol",
      "state": "Avon",
      "zip_code": "BS1 3AA",
      "marital_status": "Single",
      "next_of_kin": "Anna Miller",
      "next_of_kin_phone_number": "+44-7700-900553",
      "relationship_to_next_of_kin": "Mother",
      "next_of_kin_email": "anna.miller@example.com",
      "Right_to_Work_document_number": "UKRP223344",
      "Right_to_Work_document_expiry_date": "2034-09-09",
      "dbs_type": "Enhanced",
      "dbs_certificate_number": "DBS999000",
      "dbs_issue_date": "2025-02-15",
      "bank_name": "Monzo Bank",
      "account_number": "9999000011",
      "account_name": "Tommen Baratheon",
      "account_type": "Current",
      "is_driver": false
    }
  },
  {
    "email": "qwertyjaime.lannister@example.com",
    "password": "StrongPass456$",
    "first_name": "Jaime",
    "last_name": "Lannister",
    "role": "investor",
    "job_role": "Project Manager",
    "has_accepted_terms": true,
    "permission_levels": [
      "read",
      "write",
      "approve"
    ],
    "profile": {
      "work_phone": "+44-7700-900111",
      "personal_phone": "+44-7700-900112",
      "gender": "Female",
      "dob": "1991-02-14",
      "street": "15 Oak Avenue",
      "city": "Manchester",
      "state": "Greater Manchester",
      "zip_code": "M1 2AB",
      "marital_status": "Single",
      "next_of_kin": "Sarah Watson",
      "next_of_kin_phone_number": "+44-7700-900113",
      "relationship_to_next_of_kin": "Sister",
      "next_of_kin_email": "sarah.watson@example.com",
      "Right_to_Work_document_number": "UKRP112233",
      "Right_to_Work_document_expiry_date": "2031-09-22",
      "dbs_type": "Standard",
      "dbs_certificate_number": "DBS111222",
      "dbs_issue_date": "2024-03-05",
      "bank_name": "HSBC Bank",
      "account_number": "1111222233",
      "account_name": "Jaime Lannister",
      "account_type": "Current",
      "is_driver": false
    }
  },
  {
    "email": "qwertycersei.lannister@example.com",
    "password": "StrongPass456$",
    "first_name": "Cersei",
    "last_name": "Lannister",
    "role": "investor",
    "job_role": "Project Manager",
    "has_accepted_terms": true,
    "permission_levels": [
      "read",
      "write",
      "approve"
    ],
    "profile": {
      "work_phone": "+44-7700-900221",
      "personal_phone": "+44-7700-900222",
      "gender": "Male",
      "dob": "1989-11-03",
      "street": "88 River Lane",
      "city": "Birmingham",
      "state": "West Midlands",
      "zip_code": "B1 1AA",
      "marital_status": "Married",
      "next_of_kin": "Laura Brown",
      "next_of_kin_phone_number": "+44-7700-900223",
      "relationship_to_next_of_kin": "Wife",
      "next_of_kin_email": "laura.brown@example.com",
      "Right_to_Work_document_number": "UKRP445566",
      "Right_to_Work_document_expiry_date": "2030-07-10",
      "dbs_type": "Enhanced",
      "dbs_certificate_number": "DBS333444",
      "dbs_issue_date": "2025-01-17",
      "bank_name": "Lloyds Bank",
      "account_number": "3333444455",
      "account_name": "Cersei Lannister",
      "account_type": "Savings",
      "is_driver": true
    }
  },
  {
    "email": "qwertytyrion.lannister@example.com",
    "password": "StrongPass456$",
    "first_name": "Tyrion",
    "last_name": "Lannister",
    "role": "investor",
    "job_role": "Project Manager",
    "has_accepted_terms": true,
    "permission_levels": [
      "read",
      "write",
      "approve"
    ],
    "profile": {
      "work_phone": "+44-7700-900331",
      "personal_phone": "+44-7700-900332",
      "gender": "Female",
      "dob": "1994-04-08",
      "street": "29 King Street",
      "city": "Leeds",
      "state": "West Yorkshire",
      "zip_code": "LS1 4AA",
      "marital_status": "Single",
      "next_of_kin": "Michael Smith",
      "next_of_kin_phone_number": "+44-7700-900333",
      "relationship_to_next_of_kin": "Brother",
      "next_of_kin_email": "michael.smith@example.com",
      "Right_to_Work_document_number": "UKRP778899",
      "Right_to_Work_document_expiry_date": "2033-03-12",
      "dbs_type": "Basic",
      "dbs_certificate_number": "DBS555666",
      "dbs_issue_date": "2023-11-22",
      "bank_name": "NatWest Bank",
      "account_number": "5555666677",
      "account_name": "Tyrion Lannister",
      "account_type": "Current",
      "is_driver": false
    }
  },
  {
    "email": "qwertytywin.lannister@example.com",
    "password": "StrongPass456$",
    "first_name": "Tywin",
    "last_name": "Lannister",
    "role": "investor",
    "job_role": "Project Manager",
    "has_accepted_terms": true,
    "permission_levels": [
      "read",
      "write",
      "approve"
    ],
    "profile": {
      "work_phone": "+44-7700-900441",
      "personal_phone": "+44-7700-900442",
      "gender": "Male",
      "dob": "1992-07-20",
      "street": "10 Bridge Road",
      "city": "Liverpool",
      "state": "Merseyside",
      "zip_code": "L1 8AA",
      "marital_status": "Married",
      "next_of_kin": "Emma Thompson",
      "next_of_kin_phone_number": "+44-7700-900443",
      "relationship_to_next_of_kin": "Wife",
      "next_of_kin_email": "emma.thompson@example.com",
      "Right_to_Work_document_number": "UKRP990011",
      "Right_to_Work_document_expiry_date": "2031-01-25",
      "dbs_type": "Standard",
      "dbs_certificate_number": "DBS777888",
      "dbs_issue_date": "2024-10-01",
      "bank_name": "Santander Bank",
      "account_number": "7777888899",
      "account_name": "Tywin Lannister",
      "account_type": "Savings",
      "is_driver": true
    }
  },
  
]

[ 
  
  {
    "email": "qwertykevan.lannister@example.com",
    "password": "StrongPass456$",
    "first_name": "Kevan",
    "last_name": "Lannister",
    "role": "investor",
    "job_role": "Project Manager",
    "has_accepted_terms": true,
    "permission_levels": [
      "read",
      "write",
      "approve"
    ],
    "profile": {
      "work_phone": "+44-7700-900551",
      "personal_phone": "+44-7700-900552",
      "gender": "Female",
      "dob": "1996-12-05",
      "street": "7 Maple Close",
      "city": "Bristol",
      "state": "Avon",
      "zip_code": "BS1 3AA",
      "marital_status": "Single",
      "next_of_kin": "Anna Miller",
      "next_of_kin_phone_number": "+44-7700-900553",
      "relationship_to_next_of_kin": "Mother",
      "next_of_kin_email": "anna.miller@example.com",
      "Right_to_Work_document_number": "UKRP223344",
      "Right_to_Work_document_expiry_date": "2034-09-09",
      "dbs_type": "Enhanced",
      "dbs_certificate_number": "DBS999000",
      "dbs_issue_date": "2025-02-15",
      "bank_name": "Monzo Bank",
      "account_number": "9999000011",
      "account_name": "Kevan Lannister",
      "account_type": "Current",
      "is_driver": false
    }
  },
  {
    "email": "qwertydaenerys.targaryen@example.com",
    "password": "StrongPass456$",
    "first_name": "Daenerys",
    "last_name": "Targaryen",
    "role": "investor",
    "job_role": "Project Manager",
    "has_accepted_terms": true,
    "permission_levels": [
      "read",
      "write",
      "approve"
    ],
    "profile": {
      "work_phone": "+44-7700-900111",
      "personal_phone": "+44-7700-900112",
      "gender": "Female",
      "dob": "1991-02-14",
      "street": "15 Oak Avenue",
      "city": "Manchester",
      "state": "Greater Manchester",
      "zip_code": "M1 2AB",
      "marital_status": "Single",
      "next_of_kin": "Sarah Watson",
      "next_of_kin_phone_number": "+44-7700-900113",
      "relationship_to_next_of_kin": "Sister",
      "next_of_kin_email": "sarah.watson@example.com",
      "Right_to_Work_document_number": "UKRP112233",
      "Right_to_Work_document_expiry_date": "2031-09-22",
      "dbs_type": "Standard",
      "dbs_certificate_number": "DBS111222",
      "dbs_issue_date": "2024-03-05",
      "bank_name": "HSBC Bank",
      "account_number": "1111222233",
      "account_name": "Daenerys Targaryen",
      "account_type": "Current",
      "is_driver": false
    }
  },
  {
    "email": "qwertyviserys.targaryen@example.com",
    "password": "StrongPass456$",
    "first_name": "Viserys",
    "last_name": "Targaryen",
    "role": "investor",
    "job_role": "Project Manager",
    "has_accepted_terms": true,
    "permission_levels": [
      "read",
      "write",
      "approve"
    ],
    "profile": {
      "work_phone": "+44-7700-900221",
      "personal_phone": "+44-7700-900222",
      "gender": "Male",
      "dob": "1989-11-03",
      "street": "88 River Lane",
      "city": "Birmingham",
      "state": "West Midlands",
      "zip_code": "B1 1AA",
      "marital_status": "Married",
      "next_of_kin": "Laura Brown",
      "next_of_kin_phone_number": "+44-7700-900223",
      "relationship_to_next_of_kin": "Wife",
      "next_of_kin_email": "laura.brown@example.com",
      "Right_to_Work_document_number": "UKRP445566",
      "Right_to_Work_document_expiry_date": "2030-07-10",
      "dbs_type": "Enhanced",
      "dbs_certificate_number": "DBS333444",
      "dbs_issue_date": "2025-01-17",
      "bank_name": "Lloyds Bank",
      "account_number": "3333444455",
      "account_name": "Viserys Targaryen",
      "account_type": "Savings",
      "is_driver": true
    }
  },
  {
    "email": "qwertyaemon.targaryen@example.com",
    "password": "StrongPass456$",
    "first_name": "Aemon",
    "last_name": "Targaryen",
    "role": "investor",
    "job_role": "Project Manager",
    "has_accepted_terms": true,
    "permission_levels": [
      "read",
      "write",
      "approve"
    ],
    "profile": {
      "work_phone": "+44-7700-900331",
      "personal_phone": "+44-7700-900332",
      "gender": "Female",
      "dob": "1994-04-08",
      "street": "29 King Street",
      "city": "Leeds",
      "state": "West Yorkshire",
      "zip_code": "LS1 4AA",
      "marital_status": "Single",
      "next_of_kin": "Michael Smith",
      "next_of_kin_phone_number": "+44-7700-900333",
      "relationship_to_next_of_kin": "Brother",
      "next_of_kin_email": "michael.smith@example.com",
      "Right_to_Work_document_number": "UKRP778899",
      "Right_to_Work_document_expiry_date": "2033-03-12",
      "dbs_type": "Basic",
      "dbs_certificate_number": "DBS555666",
      "dbs_issue_date": "2023-11-22",
      "bank_name": "NatWest Bank",
      "account_number": "5555666677",
      "account_name": "Aemon Targaryen",
      "account_type": "Current",
      "is_driver": false
    }
  },
  {
    "email": "qwertyjorah.mormont@example.com",
    "password": "StrongPass456$",
    "first_name": "Jorah",
    "last_name": "Mormont",
    "role": "investor",
    "job_role": "Project Manager",
    "has_accepted_terms": true,
    "permission_levels": [
      "read",
      "write",
      "approve"
    ],
    "profile": {
      "work_phone": "+44-7700-900441",
      "personal_phone": "+44-7700-900442",
      "gender": "Male",
      "dob": "1992-07-20",
      "street": "10 Bridge Road",
      "city": "Liverpool",
      "state": "Merseyside",
      "zip_code": "L1 8AA",
      "marital_status": "Married",
      "next_of_kin": "Emma Thompson",
      "next_of_kin_phone_number": "+44-7700-900443",
      "relationship_to_next_of_kin": "Wife",
      "next_of_kin_email": "emma.thompson@example.com",
      "Right_to_Work_document_number": "UKRP990011",
      "Right_to_Work_document_expiry_date": "2031-01-25",
      "dbs_type": "Standard",
      "dbs_certificate_number": "DBS777888",
      "dbs_issue_date": "2024-10-01",
      "bank_name": "Santander Bank",
      "account_number": "7777888899",
      "account_name": "Jorah Mormont",
      "account_type": "Savings",
      "is_driver": true
    }
  },
  {
    "email": "qwertylyanna.mormont@example.com",
    "password": "StrongPass456$",
    "first_name": "Lyanna",
    "last_name": "Mormont",
    "role": "investor",
    "job_role": "Project Manager",
    "has_accepted_terms": true,
    "permission_levels": [
      "read",
      "write",
      "approve"
    ],
    "profile": {
      "work_phone": "+44-7700-900551",
      "personal_phone": "+44-7700-900552",
      "gender": "Female",
      "dob": "1996-12-05",
      "street": "7 Maple Close",
      "city": "Bristol",
      "state": "Avon",
      "zip_code": "BS1 3AA",
      "marital_status": "Single",
      "next_of_kin": "Anna Miller",
      "next_of_kin_phone_number": "+44-7700-900553",
      "relationship_to_next_of_kin": "Mother",
      "next_of_kin_email": "anna.miller@example.com",
      "Right_to_Work_document_number": "UKRP223344",
      "Right_to_Work_document_expiry_date": "2034-09-09",
      "dbs_type": "Enhanced",
      "dbs_certificate_number": "DBS999000",
      "dbs_issue_date": "2025-02-15",
      "bank_name": "Monzo Bank",
      "account_number": "9999000011",
      "account_name": "Lyanna Mormont",
      "account_type": "Current",
      "is_driver": false
    }
  },
  {
    "email": "qwertytheon.greyjoy@example.com",
    "password": "StrongPass456$",
    "first_name": "Theon",
    "last_name": "Greyjoy",
    "role": "investor",
    "job_role": "Project Manager",
    "has_accepted_terms": true,
    "permission_levels": [
      "read",
      "write",
      "approve"
    ],
    "profile": {
      "work_phone": "+44-7700-900111",
      "personal_phone": "+44-7700-900112",
      "gender": "Female",
      "dob": "1991-02-14",
      "street": "15 Oak Avenue",
      "city": "Manchester",
      "state": "Greater Manchester",
      "zip_code": "M1 2AB",
      "marital_status": "Single",
      "next_of_kin": "Sarah Watson",
      "next_of_kin_phone_number": "+44-7700-900113",
      "relationship_to_next_of_kin": "Sister",
      "next_of_kin_email": "sarah.watson@example.com",
      "Right_to_Work_document_number": "UKRP112233",
      "Right_to_Work_document_expiry_date": "2031-09-22",
      "dbs_type": "Standard",
      "dbs_certificate_number": "DBS111222",
      "dbs_issue_date": "2024-03-05",
      "bank_name": "HSBC Bank",
      "account_number": "1111222233",
      "account_name": "Theon Greyjoy",
      "account_type": "Current",
      "is_driver": false
    }
  },
]

[
 
 
  {
    "email": "qwertyyara.greyjoy@example.com",
    "password": "StrongPass456$",
    "first_name": "Yara",
    "last_name": "Greyjoy",
    "role": "investor",
    "job_role": "Project Manager",
    "has_accepted_terms": true,
    "permission_levels": [
      "read",
      "write",
      "approve"
    ],
    "profile": {
      "work_phone": "+44-7700-900221",
      "personal_phone": "+44-7700-900222",
      "gender": "Male",
      "dob": "1989-11-03",
      "street": "88 River Lane",
      "city": "Birmingham",
      "state": "West Midlands",
      "zip_code": "B1 1AA",
      "marital_status": "Married",
      "next_of_kin": "Laura Brown",
      "next_of_kin_phone_number": "+44-7700-900223",
      "relationship_to_next_of_kin": "Wife",
      "next_of_kin_email": "laura.brown@example.com",
      "Right_to_Work_document_number": "UKRP445566",
      "Right_to_Work_document_expiry_date": "2030-07-10",
      "dbs_type": "Enhanced",
      "dbs_certificate_number": "DBS333444",
      "dbs_issue_date": "2025-01-17",
      "bank_name": "Lloyds Bank",
      "account_number": "3333444455",
      "account_name": "Yara Greyjoy",
      "account_type": "Savings",
      "is_driver": true
    }
  },
  {
    "email": "qwertyeuron.greyjoy@example.com",
    "password": "StrongPass456$",
    "first_name": "Euron",
    "last_name": "Greyjoy",
    "role": "investor",
    "job_role": "Project Manager",
    "has_accepted_terms": true,
    "permission_levels": [
      "read",
      "write",
      "approve"
    ],
    "profile": {
      "work_phone": "+44-7700-900331",
      "personal_phone": "+44-7700-900332",
      "gender": "Female",
      "dob": "1994-04-08",
      "street": "29 King Street",
      "city": "Leeds",
      "state": "West Yorkshire",
      "zip_code": "LS1 4AA",
      "marital_status": "Single",
      "next_of_kin": "Michael Smith",
      "next_of_kin_phone_number": "+44-7700-900333",
      "relationship_to_next_of_kin": "Brother",
      "next_of_kin_email": "michael.smith@example.com",
      "Right_to_Work_document_number": "UKRP778899",
      "Right_to_Work_document_expiry_date": "2033-03-12",
      "dbs_type": "Basic",
      "dbs_certificate_number": "DBS555666",
      "dbs_issue_date": "2023-11-22",
      "bank_name": "NatWest Bank",
      "account_number": "5555666677",
      "account_name": "Euron Greyjoy",
      "account_type": "Current",
      "is_driver": false
    }
  },
  {
    "email": "qwertybalon.greyjoy@example.com",
    "password": "StrongPass456$",
    "first_name": "Balon",
    "last_name": "Greyjoy",
    "role": "investor",
    "job_role": "Project Manager",
    "has_accepted_terms": true,
    "permission_levels": [
      "read",
      "write",
      "approve"
    ],
    "profile": {
      "work_phone": "+44-7700-900441",
      "personal_phone": "+44-7700-900442",
      "gender": "Male",
      "dob": "1992-07-20",
      "street": "10 Bridge Road",
      "city": "Liverpool",
      "state": "Merseyside",
      "zip_code": "L1 8AA",
      "marital_status": "Married",
      "next_of_kin": "Emma Thompson",
      "next_of_kin_phone_number": "+44-7700-900443",
      "relationship_to_next_of_kin": "Wife",
      "next_of_kin_email": "emma.thompson@example.com",
      "Right_to_Work_document_number": "UKRP990011",
      "Right_to_Work_document_expiry_date": "2031-01-25",
      "dbs_type": "Standard",
      "dbs_certificate_number": "DBS777888",
      "dbs_issue_date": "2024-10-01",
      "bank_name": "Santander Bank",
      "account_number": "7777888899",
      "account_name": "Balon Greyjoy",
      "account_type": "Savings",
      "is_driver": true
    }
  },
  {
    "email": "qwertysamwell.tarly@example.com",
    "password": "StrongPass456$",
    "first_name": "Samwell",
    "last_name": "Tarly",
    "role": "investor",
    "job_role": "Project Manager",
    "has_accepted_terms": true,
    "permission_levels": [
      "read",
      "write",
      "approve"
    ],
    "profile": {
      "work_phone": "+44-7700-900551",
      "personal_phone": "+44-7700-900552",
      "gender": "Female",
      "dob": "1996-12-05",
      "street": "7 Maple Close",
      "city": "Bristol",
      "state": "Avon",
      "zip_code": "BS1 3AA",
      "marital_status": "Single",
      "next_of_kin": "Anna Miller",
      "next_of_kin_phone_number": "+44-7700-900553",
      "relationship_to_next_of_kin": "Mother",
      "next_of_kin_email": "anna.miller@example.com",
      "Right_to_Work_document_number": "UKRP223344",
      "Right_to_Work_document_expiry_date": "2034-09-09",
      "dbs_type": "Enhanced",
      "dbs_certificate_number": "DBS999000",
      "dbs_issue_date": "2025-02-15",
      "bank_name": "Monzo Bank",
      "account_number": "9999000011",
      "account_name": "Samwell Tarly",
      "account_type": "Current",
      "is_driver": false
    }
  },
  {
    "email": "qwertybrienne.tarth@example.com",
    "password": "StrongPass456$",
    "first_name": "Brienne",
    "last_name": "Tarth",
    "role": "investor",
    "job_role": "Project Manager",
    "has_accepted_terms": true,
    "permission_levels": [
      "read",
      "write",
      "approve"
    ],
    "profile": {
      "work_phone": "+44-7700-900111",
      "personal_phone": "+44-7700-900112",
      "gender": "Female",
      "dob": "1991-02-14",
      "street": "15 Oak Avenue",
      "city": "Manchester",
      "state": "Greater Manchester",
      "zip_code": "M1 2AB",
      "marital_status": "Single",
      "next_of_kin": "Sarah Watson",
      "next_of_kin_phone_number": "+44-7700-900113",
      "relationship_to_next_of_kin": "Sister",
      "next_of_kin_email": "sarah.watson@example.com",
      "Right_to_Work_document_number": "UKRP112233",
      "Right_to_Work_document_expiry_date": "2031-09-22",
      "dbs_type": "Standard",
      "dbs_certificate_number": "DBS111222",
      "dbs_issue_date": "2024-03-05",
      "bank_name": "HSBC Bank",
      "account_number": "1111222233",
      "account_name": "Brienne Tarth",
      "account_type": "Current",
      "is_driver": false
    }
  },
  {
    "email": "qwertysandor.clegane@example.com",
    "password": "StrongPass456$",
    "first_name": "Sandor",
    "last_name": "Clegane",
    "role": "investor",
    "job_role": "Project Manager",
    "has_accepted_terms": true,
    "permission_levels": [
      "read",
      "write",
      "approve"
    ],
    "profile": {
      "work_phone": "+44-7700-900221",
      "personal_phone": "+44-7700-900222",
      "gender": "Male",
      "dob": "1989-11-03",
      "street": "88 River Lane",
      "city": "Birmingham",
      "state": "West Midlands",
      "zip_code": "B1 1AA",
      "marital_status": "Married",
      "next_of_kin": "Laura Brown",
      "next_of_kin_phone_number": "+44-7700-900223",
      "relationship_to_next_of_kin": "Wife",
      "next_of_kin_email": "laura.brown@example.com",
      "Right_to_Work_document_number": "UKRP445566",
      "Right_to_Work_document_expiry_date": "2030-07-10",
      "dbs_type": "Enhanced",
      "dbs_certificate_number": "DBS333444",
      "dbs_issue_date": "2025-01-17",
      "bank_name": "Lloyds Bank",
      "account_number": "3333444455",
      "account_name": "Sandor Clegane",
      "account_type": "Savings",
      "is_driver": true
    }
  },
  {
    "email": "qwertygregor.clegane@example.com",
    "password": "StrongPass456$",
    "first_name": "Gregor",
    "last_name": "Clegane",
    "role": "investor",
    "job_role": "Project Manager",
    "has_accepted_terms": true,
    "permission_levels": [
      "read",
      "write",
      "approve"
    ],
    "profile": {
      "work_phone": "+44-7700-900331",
      "personal_phone": "+44-7700-900332",
      "gender": "Female",
      "dob": "1994-04-08",
      "street": "29 King Street",
      "city": "Leeds",
      "state": "West Yorkshire",
      "zip_code": "LS1 4AA",
      "marital_status": "Single",
      "next_of_kin": "Michael Smith",
      "next_of_kin_phone_number": "+44-7700-900333",
      "relationship_to_next_of_kin": "Brother",
      "next_of_kin_email": "michael.smith@example.com",
      "Right_to_Work_document_number": "UKRP778899",
      "Right_to_Work_document_expiry_date": "2033-03-12",
      "dbs_type": "Basic",
      "dbs_certificate_number": "DBS555666",
      "dbs_issue_date": "2023-11-22",
      "bank_name": "NatWest Bank",
      "account_number": "5555666677",
      "account_name": "Gregor Clegane",
      "account_type": "Current",
      "is_driver": false
    }
  },
  {
    "email": "qwertydavos.seaworth@example.com",
    "password": "StrongPass456$",
    "first_name": "Davos",
    "last_name": "Seaworth",
    "role": "investor",
    "job_role": "Project Manager",
    "has_accepted_terms": true,
    "permission_levels": [
      "read",
      "write",
      "approve"
    ],
    "profile": {
      "work_phone": "+44-7700-900441",
      "personal_phone": "+44-7700-900442",
      "gender": "Male",
      "dob": "1992-07-20",
      "street": "10 Bridge Road",
      "city": "Liverpool",
      "state": "Merseyside",
      "zip_code": "L1 8AA",
      "marital_status": "Married",
      "next_of_kin": "Emma Thompson",
      "next_of_kin_phone_number": "+44-7700-900443",
      "relationship_to_next_of_kin": "Wife",
      "next_of_kin_email": "emma.thompson@example.com",
      "Right_to_Work_document_number": "UKRP990011",
      "Right_to_Work_document_expiry_date": "2031-01-25",
      "dbs_type": "Standard",
      "dbs_certificate_number": "DBS777888",
      "dbs_issue_date": "2024-10-01",
      "bank_name": "Santander Bank",
      "account_number": "7777888899",
      "account_name": "Davos Seaworth",
      "account_type": "Savings",
      "is_driver": true
    }
  },
]



[{
    "email": "qwertysteelshanks.walton@example.com",
    "password": "StrongPass456$",
    "first_name": "Steelshanks",
    "last_name": "Walton",
    "role": "investor",
    "job_role": "Project Manager",
    "has_accepted_terms": true,
    "permission_levels": [
      "read",
      "write",
      "approve"
    ],
    "profile": {
      "work_phone": "+44-7700-900551",
      "personal_phone": "+44-7700-900552",
      "gender": "Female",
      "dob": "1996-12-05",
      "street": "7 Maple Close",
      "city": "Bristol",
      "state": "Avon",
      "zip_code": "BS1 3AA",
      "marital_status": "Single",
      "next_of_kin": "Anna Miller",
      "next_of_kin_phone_number": "+44-7700-900553",
      "relationship_to_next_of_kin": "Mother",
      "next_of_kin_email": "anna.miller@example.com",
      "Right_to_Work_document_number": "UKRP223344",
      "Right_to_Work_document_expiry_date": "2034-09-09",
      "dbs_type": "Enhanced",
      "dbs_certificate_number": "DBS999000",
      "dbs_issue_date": "2025-02-15",
      "bank_name": "Monzo Bank",
      "account_number": "9999000011",
      "account_name": "Steelshanks Walton",
      "account_type": "Current",
      "is_driver": false
    }
  },
  {
    "email": "qwertyleaf.children@example.com",
    "password": "StrongPass456$",
    "first_name": "Leaf",
    "last_name": "Children",
    "role": "investor",
    "job_role": "Project Manager",
    "has_accepted_terms": true,
    "permission_levels": [
      "read",
      "write",
      "approve"
    ],
    "profile": {
      "work_phone": "+44-7700-900111",
      "personal_phone": "+44-7700-900112",
      "gender": "Female",
      "dob": "1991-02-14",
      "street": "15 Oak Avenue",
      "city": "Manchester",
      "state": "Greater Manchester",
      "zip_code": "M1 2AB",
      "marital_status": "Single",
      "next_of_kin": "Sarah Watson",
      "next_of_kin_phone_number": "+44-7700-900113",
      "relationship_to_next_of_kin": "Sister",
      "next_of_kin_email": "sarah.watson@example.com",
      "Right_to_Work_document_number": "UKRP112233",
      "Right_to_Work_document_expiry_date": "2031-09-22",
      "dbs_type": "Standard",
      "dbs_certificate_number": "DBS111222",
      "dbs_issue_date": "2024-03-05",
      "bank_name": "HSBC Bank",
      "account_number": "1111222233",
      "account_name": "Leaf Children",
      "account_type": "Current",
      "is_driver": false
    }
  },
  {
    "email": "qwertyaeron.greyjoy@example.com",
    "password": "StrongPass456$",
    "first_name": "Aeron",
    "last_name": "Greyjoy",
    "role": "investor",
    "job_role": "Project Manager",
    "has_accepted_terms": true,
    "permission_levels": [
      "read",
      "write",
      "approve"
    ],
    "profile": {
      "work_phone": "+44-7700-900221",
      "personal_phone": "+44-7700-900222",
      "gender": "Male",
      "dob": "1989-11-03",
      "street": "88 River Lane",
      "city": "Birmingham",
      "state": "West Midlands",
      "zip_code": "B1 1AA",
      "marital_status": "Married",
      "next_of_kin": "Laura Brown",
      "next_of_kin_phone_number": "+44-7700-900223",
      "relationship_to_next_of_kin": "Wife",
      "next_of_kin_email": "laura.brown@example.com",
      "Right_to_Work_document_number": "UKRP445566",
      "Right_to_Work_document_expiry_date": "2030-07-10",
      "dbs_type": "Enhanced",
      "dbs_certificate_number": "DBS333444",
      "dbs_issue_date": "2025-01-17",
      "bank_name": "Lloyds Bank",
      "account_number": "3333444455",
      "account_name": "Aeron Greyjoy",
      "account_type": "Savings",
      "is_driver": true
    }
  },
  {
    "email": "qwertysyrio.forel@example.com",
    "password": "StrongPass456$",
    "first_name": "Syrio",
    "last_name": "Forel",
    "role": "investor",
    "job_role": "Project Manager",
    "has_accepted_terms": true,
    "permission_levels": [
      "read",
      "write",
      "approve"
    ],
    "profile": {
      "work_phone": "+44-7700-900331",
      "personal_phone": "+44-7700-900332",
      "gender": "Female",
      "dob": "1994-04-08",
      "street": "29 King Street",
      "city": "Leeds",
      "state": "West Yorkshire",
      "zip_code": "LS1 4AA",
      "marital_status": "Single",
      "next_of_kin": "Michael Smith",
      "next_of_kin_phone_number": "+44-7700-900333",
      "relationship_to_next_of_kin": "Brother",
      "next_of_kin_email": "michael.smith@example.com",
      "Right_to_Work_document_number": "UKRP778899",
      "Right_to_Work_document_expiry_date": "2033-03-12",
      "dbs_type": "Basic",
      "dbs_certificate_number": "DBS555666",
      "dbs_issue_date": "2023-11-22",
      "bank_name": "NatWest Bank",
      "account_number": "5555666677",
      "account_name": "Syrio Forel",
      "account_type": "Current",
      "is_driver": false
    }
  },
  {
    "email": "qwertykraznys.nakloz@example.com",
    "password": "StrongPass456$",
    "first_name": "Kraznys",
    "last_name": "Nakloz",
    "role": "investor",
    "job_role": "Project Manager",
    "has_accepted_terms": true,
    "permission_levels": [
      "read",
      "write",
      "approve"
    ],
    "profile": {
      "work_phone": "+44-7700-900441",
      "personal_phone": "+44-7700-900442",
      "gender": "Male",
      "dob": "1992-07-20",
      "street": "10 Bridge Road",
      "city": "Liverpool",
      "state": "Merseyside",
      "zip_code": "L1 8AA",
      "marital_status": "Married",
      "next_of_kin": "Emma Thompson",
      "next_of_kin_phone_number": "+44-7700-900443",
      "relationship_to_next_of_kin": "Wife",
      "next_of_kin_email": "emma.thompson@example.com",
      "Right_to_Work_document_number": "UKRP990011",
      "Right_to_Work_document_expiry_date": "2031-01-25",
      "dbs_type": "Standard",
      "dbs_certificate_number": "DBS777888",
      "dbs_issue_date": "2024-10-01",
      "bank_name": "Santander Bank",
      "account_number": "7777888899",
      "account_name": "Kraznys Nakloz",
      "account_type": "Savings",
      "is_driver": true
    }
  },
  {
    "email": "qwertywill.bran@example.com",
    "password": "StrongPass456$",
    "first_name": "Will",
    "last_name": "Bran",
    "role": "investor",
    "job_role": "Project Manager",
    "has_accepted_terms": true,
    "permission_levels": [
      "read",
      "write",
      "approve"
    ],
    "profile": {
      "work_phone": "+44-7700-900551",
      "personal_phone": "+44-7700-900552",
      "gender": "Female",
      "dob": "1996-12-05",
      "street": "7 Maple Close",
      "city": "Bristol",
      "state": "Avon",
      "zip_code": "BS1 3AA",
      "marital_status": "Single",
      "next_of_kin": "Anna Miller",
      "next_of_kin_phone_number": "+44-7700-900553",
      "relationship_to_next_of_kin": "Mother",
      "next_of_kin_email": "anna.miller@example.com",
      "Right_to_Work_document_number": "UKRP223344",
      "Right_to_Work_document_expiry_date": "2034-09-09",
      "dbs_type": "Enhanced",
      "dbs_certificate_number": "DBS999000",
      "dbs_issue_date": "2025-02-15",
      "bank_name": "Monzo Bank",
      "account_number": "9999000011",
      "account_name": "Will Bran",
      "account_type": "Current",
      "is_driver": false
    }
  },
  {
    "email": "qwertyrickard.karstark@example.com",
    "password": "StrongPass456$",
    "first_name": "Rickard",
    "last_name": "Karstark",
    "role": "investor",
    "job_role": "Project Manager",
    "has_accepted_terms": true,
    "permission_levels": [
      "read",
      "write",
      "approve"
    ],
    "profile": {
      "work_phone": "+44-7700-900111",
      "personal_phone": "+44-7700-900112",
      "gender": "Female",
      "dob": "1991-02-14",
      "street": "15 Oak Avenue",
      "city": "Manchester",
      "state": "Greater Manchester",
      "zip_code": "M1 2AB",
      "marital_status": "Single",
      "next_of_kin": "Sarah Watson",
      "next_of_kin_phone_number": "+44-7700-900113",
      "relationship_to_next_of_kin": "Sister",
      "next_of_kin_email": "sarah.watson@example.com",
      "Right_to_Work_document_number": "UKRP112233",
      "Right_to_Work_document_expiry_date": "2031-09-22",
      "dbs_type": "Standard",
      "dbs_certificate_number": "DBS111222",
      "dbs_issue_date": "2024-03-05",
      "bank_name": "HSBC Bank",
      "account_number": "1111222233",
      "account_name": "Rickard Karstark",
      "account_type": "Current",
      "is_driver": false
    }
  }
]