# Generated by Django 5.2.5 on 2025-11-05 14:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.CharField(editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('tenant_id', models.CharField(max_length=36)),
                ('job_requisition_id', models.CharField(max_length=36)),
                ('job_requisition_title', models.CharField(max_length=255)),
                ('branch_id', models.CharField(blank=True, max_length=36, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('resume_url', models.TextField()),
                ('cover_letter_url', models.TextField(blank=True, null=True)),
                ('resume_status', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('career_site', 'Career Site'), ('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('referral', 'Referral'), ('agency', 'Agency'), ('other', 'Other')], default='career_site', max_length=20)),
                ('referred_by', models.CharField(blank=True, max_length=36, null=True)),
                ('application_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_stage', models.CharField(choices=[('application', 'Application'), ('screening', 'Screening'), ('interview', 'Interview'), ('offer', 'Offer'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('compliance_completed', 'Compliance Completed'), ('compliance_failed', 'Compliance Failed'), ('onboarded', 'Onboarded')], default='application', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('shortlisted', 'Shortlisted'), ('interviewing', 'Interviewing'), ('interviewed', 'Interviewed'), ('offer_pending', 'Offer Pending'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('onboarded', 'Onboarded'), ('compliance_completed', 'Compliance Completed'), ('compliance_failed', 'Compliance Failed')], default='new', max_length=20)),
                ('status_history', models.JSONField(blank=True, default=list)),
                ('hired_by', models.JSONField(blank=True, default=dict, null=True)),
                ('ai_vetting_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_vetting_notes', models.JSONField(blank=True, default=dict)),
                ('screening_status', models.JSONField(blank=True, default=list)),
                ('screening_score', models.FloatField(blank=True, null=True)),
                ('screening_questions', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('qualification', models.TextField(blank=True, max_length=255, null=True)),
                ('experience', models.TextField(blank=True, max_length=255, null=True)),
                ('knowledge_skill', models.TextField(blank=True, null=True)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('employment_gaps', models.JSONField(blank=True, default=list)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('compliance_status', models.JSONField(blank=True, default=list)),
                ('interview_location', models.CharField(blank=True, max_length=255, null=True)),
                ('disposition_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'job_applications_job_application',
                'indexes': [models.Index(fields=['tenant_id', 'job_requisition_id'], name='idx_candidates_tenant'), models.Index(fields=['status', 'current_stage'], name='idx_candidates_status'), models.Index(fields=['email', 'tenant_id'], name='idx_candidates_email'), models.Index(fields=['-ai_vetting_score'], name='idx_candidates_vetting')],
                'unique_together': {('tenant_id', 'job_requisition_id', 'email', 'branch_id')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.CharField(editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('tenant_id', models.CharField(max_length=36)),
                ('branch_id', models.CharField(blank=True, max_length=36, null=True)),
                ('job_application_id', models.CharField(max_length=36)),
                ('job_requisition_title', models.CharField(max_length=255)),
                ('scheduled_by_id', models.CharField(blank=True, max_length=36, null=True)),
                ('interview_start_date_time', models.DateTimeField()),
                ('interview_end_date_time', models.DateTimeField(blank=True, null=True)),
                ('meeting_mode', models.CharField(choices=[('Virtual', 'Virtual'), ('Physical', 'Physical')], max_length=20)),
                ('meeting_link', models.URLField(blank=True, max_length=255, null=True)),
                ('interview_address', models.TextField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('timezone', models.CharField(choices=[('UTC', 'UTC'), ('America/New_York', 'Eastern Time (US)'), ('America/Chicago', 'Central Time (US)'), ('America/Los_Angeles', 'Pacific Time (US)'), ('Europe/London', 'London'), ('Asia/Tokyo', 'Tokyo')], default='UTC', max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'job_applications_schedule',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('status', 'scheduled')), fields=('job_application_id',), name='unique_active_schedule_per_application')],
                'unique_together': {('tenant_id', 'job_application_id', 'interview_start_date_time', 'branch_id')},
            },
        ),
    ]
