# Generated by Django 5.2.5 on 2025-09-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='hired_by',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('shortlisted', 'Shortlisted'), ('interviewing', 'Interviewing'), ('interviewed', 'Interviewed'), ('offer_pending', 'Offer Pending'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('onboarded', 'Onboarded')], default='new', max_length=20),
        ),
    ]
