# Generated by Django 5.2.5 on 2025-10-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='job_requisition_title',
            field=models.CharField(default='Untitled Job Requisition', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='job_requisition_title',
            field=models.CharField(default='Untitled', max_length=255),
            preserve_default=False,
        ),
    ]
