# Generated by Django 5.2.5 on 2025-09-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('shortlisted', 'Shortlisted'), ('interviewing', 'Interviewing'), ('interviewed', 'Interviewed'), ('offer_pending', 'Offer Pending'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='new', max_length=20),
        ),
    ]
