# Generated by Django 5.2.5 on 2025-09-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0002_remove_jobapplication_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='scheduled_by_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
