# Generated by Django 5.2.5 on 2025-10-01 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0002_jobapplication_hired_by_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='status_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
