# Generated by Django 5.2.5 on 2025-09-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0003_schedule_scheduled_by_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='job_application_id',
            field=models.CharField(max_length=36),
        ),
    ]
