# Generated by Django 5.2.5 on 2025-09-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0004_alter_schedule_job_application_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='id',
            field=models.CharField(editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
