# Generated by Django 5.2.5 on 2025-09-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0005_alter_schedule_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='current_stage',
            field=models.CharField(choices=[('application', 'Application'), ('screening', 'Screening'), ('interview', 'Interview'), ('offer', 'Offer'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('compliance_completed', 'Compliance Completed')], default='application', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('shortlisted', 'Shortlisted'), ('interviewing', 'Interviewing'), ('interviewed', 'Interviewed'), ('offer_pending', 'Offer Pending'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('compliance_completed', 'Compliance Completed')], default='new', max_length=20),
        ),
    ]
