# Generated by Django 5.2.5 on 2025-09-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0006_alter_jobapplication_current_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('shortlisted', 'Shortlisted'), ('interviewing', 'Interviewing'), ('interviewed', 'Interviewed'), ('offer_pending', 'Offer Pending'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('withdrawn', 'Withdrawn'), ('onboarded', 'Onboarded')], default='new', max_length=20),
        ),
    ]
