# Generated by Django 5.2.2 on 2025-08-11 16:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(choices=[('talent_engine', 'Talent Engine'), ('compliance', 'Compliance'), ('training', 'Training'), ('care_coordination', 'Care Coordination'), ('workforce', 'Workforce'), ('analytics', 'Analytics'), ('integrations', 'Integrations')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.tenant')),
            ],
            options={
                'db_table': 'subscriptions_subscription',
                'unique_together': {('tenant', 'module')},
            },
        ),
    ]
