# Generated by Django 5.2.5 on 2025-11-06 10:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unique_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('qr_data', models.TextField()),
                ('image_url', models.URLField(blank=True)),
                ('scan_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actual_scan_count', models.PositiveIntegerField(default=0, help_text='Number of times the QR code was actually scanned and form loaded')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrcodes', to='core.tenant')),
            ],
            options={
                'db_table': 'reviews_qrcode',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reviewer_name', models.CharField(blank=True, max_length=255)),
                ('reviewer_email', models.EmailField(blank=True, max_length=254)),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('is_anonymous', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('sentiment_subjectivity', models.FloatField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reviews', to=settings.AUTH_USER_MODEL)),
                ('qr_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='reviews.qrcode')),
                ('reviewer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.tenant')),
            ],
            options={
                'db_table': 'reviews_review',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_anonymous', models.BooleanField(default=True)),
                ('max_attachments', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('approval_required', models.BooleanField(default=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_settings', to='core.tenant')),
            ],
            options={
                'db_table': 'reviews_reviewsettings',
            },
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['tenant', 'is_active', 'created_at'], name='reviews_qrc_tenant__87cf08_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['tenant', 'is_approved', 'submitted_at'], name='reviews_rev_tenant__2853de_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['qr_code', 'submitted_at'], name='reviews_rev_qr_code_356a35_idx'),
        ),
    ]
