# Generated by Django 5.2.5 on 2025-11-05 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='qr_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='reviews.qrcode'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='reviewsettings',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_settings', to='core.tenant'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['tenant', 'is_active', 'created_at'], name='reviews_qrc_tenant__87cf08_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['tenant', 'is_approved', 'submitted_at'], name='reviews_rev_tenant__2853de_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['qr_code', 'submitted_at'], name='reviews_rev_qr_code_356a35_idx'),
        ),
    ]
