# Generated by Django 5.2.5 on 2025-09-26 08:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(max_length=36)),
                ('branch_id', models.CharField(blank=True, max_length=36, null=True)),
                ('requested_by_id', models.CharField(blank=True, max_length=36, null=True)),
                ('request_type', models.CharField(choices=[('material', 'Material Request'), ('leave', 'Leave Request')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Extra details specific to the request type')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'crm_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_application_id', models.CharField(max_length=20)),
                ('tenant_id', models.CharField(max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('meeting_id', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('scores', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'video_session',
            },
        ),
        migrations.CreateModel(
            name='JobRequisition',
            fields=[
                ('tenant_name', models.CharField(blank=True, help_text='Tenant name for code generation', max_length=255, null=True)),
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('requisition_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('job_requisition_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('job_application_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('last_compliance_check', models.DateTimeField(blank=True, null=True)),
                ('checked_by', models.CharField(blank=True, max_length=255, null=True)),
                ('tenant_id', models.CharField(max_length=255)),
                ('branch_id', models.CharField(blank=True, max_length=36, null=True)),
                ('department_id', models.CharField(blank=True, max_length=36, null=True)),
                ('hiring_manager_id', models.CharField(blank=True, max_length=36, null=True)),
                ('title', models.CharField(max_length=255)),
                ('unique_link', models.CharField(blank=True, editable=False, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('on_hold', 'On Hold')], default='pending', max_length=20)),
                ('role', models.CharField(choices=[('staff', 'Staff'), ('admin', 'Admin')], default='staff', max_length=20)),
                ('requested_by_id', models.CharField(blank=True, max_length=36, null=True)),
                ('approved_by_id', models.CharField(blank=True, max_length=36, null=True)),
                ('created_by_id', models.CharField(blank=True, max_length=36, null=True)),
                ('updated_by_id', models.CharField(blank=True, max_length=36, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('job_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('temporary', 'Temporary')], default='full_time', max_length=20)),
                ('position_type', models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('internship', 'Internship')], default='permanent', max_length=20)),
                ('location_type', models.CharField(choices=[('on_site', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='on_site', max_length=20)),
                ('job_location', models.TextField(blank=True, null=True)),
                ('interview_location', models.CharField(blank=True, max_length=255)),
                ('salary_range', models.CharField(blank=True, max_length=255, null=True)),
                ('salary_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('qualification_requirement', models.TextField(blank=True, null=True)),
                ('experience_requirement', models.TextField(blank=True, null=True)),
                ('knowledge_requirement', models.TextField(blank=True, null=True)),
                ('number_of_candidates', models.IntegerField(blank=True, null=True)),
                ('num_of_applications', models.IntegerField(blank=True, default=0, null=True)),
                ('urgency_level', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('deadline_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('responsibilities', models.JSONField(blank=True, default=list)),
                ('compliance_checklist', models.JSONField(blank=True, default=list)),
                ('documents_required', models.JSONField(blank=True, default=list)),
                ('approval_workflow', models.JSONField(blank=True, default=dict)),
                ('current_approval_stage', models.IntegerField(default=0)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('time_to_fill_days', models.IntegerField(blank=True, null=True)),
                ('advert_banner', models.ImageField(blank=True, max_length=512, null=True, upload_to='advert_banners/')),
                ('advert_banner_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('requested_date', models.DateField(auto_now_add=True)),
                ('publish_status', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True, help_text='User comment for the Job Requisition', null=True)),
            ],
            options={
                'db_table': 'talent_engine_job_requisition',
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='idx_req_tenant_status'), models.Index(fields=['department_id', 'job_type'], name='idx_req_department'), models.Index(fields=['requested_by_id', 'approval_date'], name='idx_req_approval')],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=36, null=True)),
                ('candidate_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('is_muted', models.BooleanField(default=False)),
                ('is_camera_on', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='jobRequisitions.videosession')),
            ],
            options={
                'db_table': 'video_participant',
            },
        ),
    ]
