# Generated by Django 5.2.5 on 2025-08-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobRequisitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequisition',
            name='hiring_manager_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
