# Generated by Django 5.2.5 on 2025-10-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobRequisitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='cancelled_by_details',
            field=models.JSONField(blank=True, default=dict, help_text='Details of the user who cancelled the request', null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='cancelled_by_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='rejected_by_details',
            field=models.JSONField(blank=True, default=dict, help_text='Details of the user who rejected the request', null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='rejected_by_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
