# Generated by Django 5.2.5 on 2025-09-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobRequisitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='approved_by_details',
            field=models.JSONField(blank=True, default=dict, help_text='Details of the user who approved the request', null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='approved_by_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
