# Generated by Django 5.2.5 on 2025-08-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobRequisitions', '0002_jobrequisition_hiring_manager_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequisition',
            name='tenant_name',
            field=models.CharField(blank=True, help_text='Tenant name for code generation', max_length=100, null=True),
        ),
    ]
