# Generated by Django 5.2.5 on 2025-09-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobRequisitions', '0003_jobrequisition_tenant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequisition',
            name='num_of_applications',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
