# Generated by Django 5.2.5 on 2025-09-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobRequisitions', '0004_jobrequisition_num_of_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequisition',
            name='tenant_name',
            field=models.CharField(blank=True, help_text='Tenant name for code generation', max_length=255, null=True),
        ),
    ]
