# Generated by Django 5.2.5 on 2025-09-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobRequisitions', '0005_alter_jobrequisition_tenant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequisition',
            name='salary_range',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
