# Generated by Django 5.2.5 on 2025-10-07 10:44

import jobRequisitions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobRequisitions', '0005_remove_jobrequisition_branch_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequisition',
            name='compliance_checklist',
            field=models.JSONField(blank=True, default=list, validators=[jobRequisitions.models.validate_compliance_checklist]),
        ),
    ]
