# Generated by Django 5.2.5 on 2025-09-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobRequisitions', '0006_alter_jobrequisition_salary_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequisition',
            name='advert_banner',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='advert_banners/'),
        ),
    ]
