# Generated by Django 5.2.5 on 2025-09-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobRequisitions', '0007_alter_jobrequisition_advert_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequisition',
            name='advert_banner_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='jobrequisition',
            name='advert_banner',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to='advert_banners/'),
        ),
    ]
