# Generated by Django 5.2.5 on 2025-09-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobRequisitions', '0008_jobrequisition_advert_banner_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequisition',
            name='tenant_id',
            field=models.CharField(max_length=255),
        ),
    ]
