# Generated by Django 5.2.5 on 2025-09-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobRequisitions', '0009_alter_jobrequisition_tenant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequisition',
            name='compliance_checklist',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
