# Generated by Django 5.2.5 on 2025-12-22 04:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('role', models.CharField(default='super-admin', max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('login_attempts', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('has_accepted_terms', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Global User',
                'verbose_name_plural': 'Global Users',
                'db_table': 'core_globaluser',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('overdue', 'Overdue')], default='active', help_text='Tenant suspension status', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('schema_name', models.CharField(max_length=63, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizational_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('email_host', models.CharField(blank=True, max_length=255, null=True)),
                ('email_port', models.IntegerField(blank=True, null=True)),
                ('email_use_ssl', models.BooleanField(default=True)),
                ('email_host_user', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_host_password', models.CharField(blank=True, max_length=255, null=True)),
                ('default_from_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('about_us', models.TextField(blank=True, null=True)),
                ('primary_color', models.CharField(default='#FF0000', help_text='Tenant primary theme color in HEX format', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid hex code (e.g. #FF0000)', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('secondary_color', models.CharField(default='#FADBD8', help_text='Tenant secondary theme color in HEX format', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid hex code (e.g. #FF0000)', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('account_name', models.CharField(blank=True, help_text='Bank account name', max_length=255, null=True)),
                ('bank_name', models.CharField(blank=True, help_text='Bank name', max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, help_text='Bank account number', max_length=50, null=True)),
                ('roi_percent', models.DecimalField(decimal_places=2, default=40.0, help_text='Annual ROI percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('roi_frequency', models.CharField(choices=[('Monthly', 'Monthly'), ('On Demand', 'On Demand')], default='Monthly', help_text='ROI payment frequency', max_length=20)),
                ('min_withdrawal_months', models.PositiveIntegerField(default=4, help_text='Minimum months before principal withdrawal')),
                ('unique_policy_prefix', models.CharField(default='APP', help_text='Prefix for unique policy numbers', max_length=10)),
                ('next_policy_number', models.PositiveIntegerField(default=200000, help_text='Next available policy number')),
                ('kyc_method', models.CharField(choices=[('passport', 'Passport Only'), ('passport_utility', 'Passport + Utility Bill'), ('passport_id', 'Passport + Government ID'), ('passport_utility_id', 'Passport + Utility Bill + Government ID'), ('custom', 'Other (specify)')], default='passport', help_text='KYC verification requirements', max_length=20)),
                ('kyc_custom', models.TextField(blank=True, help_text='Custom KYC requirements description', null=True)),
            ],
            options={
                'db_table': 'core_tenant',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIDecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_type', models.CharField(max_length=100)),
                ('confidence_score', models.FloatField()),
                ('model_version', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.URLField(blank=True, null=True)),
                ('custom_fields', models.JSONField(default=dict)),
                ('email_templates', models.JSONField(default=dict)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='UsernameIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150, unique=True)),
                ('user_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'public_usernameindex',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('hr', 'HR'), ('carer', 'Carer'), ('client', 'Client'), ('family', 'Family'), ('auditor', 'Auditor'), ('tutor', 'Tutor'), ('assessor', 'Assessor'), ('iqa', 'IQA'), ('eqa', 'EQA'), ('recruiter', 'Recruiter'), ('team_manager', 'Team Manager')], max_length=20)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.module')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'unique_together': {('role', 'module', 'tenant')},
            },
        ),
        migrations.CreateModel(
            name='GlobalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_user', models.CharField(blank=True, help_text='Super-admin user ID from public tenant', max_length=36, null=True)),
                ('action', models.CharField(choices=[('platform_user_created', 'Platform User Created'), ('platform_user_updated', 'Platform User Updated'), ('platform_user_deleted', 'Platform User Deleted'), ('tenant_created', 'Tenant Created'), ('tenant_updated', 'Tenant Updated'), ('tenant_deleted', 'Tenant Deleted'), ('tenant_suspended', 'Tenant Suspended'), ('tenant_activated', 'Tenant Activated'), ('global_keypair_generated', 'Global Keypair Generated'), ('system_backup_created', 'System Backup Created'), ('audit_export_requested', 'Audit Export Requested'), ('tenant_quota_exceeded', 'Tenant Quota Exceeded'), ('global_login_failed', 'Global Login Failed'), ('security_alert_triggered', 'Security Alert Triggered')], max_length=50)),
                ('performed_by', models.CharField(blank=True, help_text='User ID who performed the action', max_length=36, null=True)),
                ('global_correlation_id', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('success', models.BooleanField(help_text='Indicates if the action was successful.', null=True)),
                ('affected_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_activities', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Global Activity',
                'verbose_name_plural': 'Global Activities',
                'db_table': 'core_globalactivity',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['affected_tenant', 'timestamp'], name='core_global_affecte_39b309_idx'), models.Index(fields=['affected_tenant', 'action', 'timestamp'], name='core_global_affecte_f0f7f0_idx'), models.Index(fields=['global_user', 'timestamp'], name='core_global_global__5b573a_idx'), models.Index(fields=['performed_by', 'timestamp'], name='core_global_perform_7cd440_idx'), models.Index(fields=['success', 'timestamp'], name='core_global_success_715c92_idx'), models.Index(fields=['timestamp'], name='core_global_timesta_1573cc_idx'), models.Index(fields=['global_correlation_id'], name='core_global_global__168f55_idx')],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_head_office', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'name')},
            },
        ),
    ]
