# Generated by Django 5.2.2 on 2025-07-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='about_us',
            field=models.TextField(blank=True, null=True),
        ),
    ]
