# Generated by Django 5.2.5 on 2025-10-30 16:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('role', models.CharField(default='super-admin', max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('login_attempts', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('has_accepted_terms', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Global User',
                'verbose_name_plural': 'Global Users',
                'db_table': 'core_globaluser',
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='account_name',
            field=models.CharField(blank=True, help_text='Bank account name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='account_number',
            field=models.CharField(blank=True, help_text='Bank account number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='kyc_custom',
            field=models.TextField(blank=True, help_text='Custom KYC requirements description', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='kyc_method',
            field=models.CharField(choices=[('passport', 'Passport Only'), ('passport_utility', 'Passport + Utility Bill'), ('passport_id', 'Passport + Government ID'), ('passport_utility_id', 'Passport + Utility Bill + Government ID'), ('custom', 'Other (specify)')], default='passport', help_text='KYC verification requirements', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='min_withdrawal_months',
            field=models.PositiveIntegerField(default=4, help_text='Minimum months before principal withdrawal'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='next_policy_number',
            field=models.PositiveIntegerField(default=200000, help_text='Next available policy number'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='primary_color',
            field=models.CharField(default='#FF0000', help_text='Tenant primary theme color in HEX format', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid hex code (e.g. #FF0000)', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='roi_frequency',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('On Demand', 'On Demand')], default='Monthly', help_text='ROI payment frequency', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='roi_percent',
            field=models.DecimalField(decimal_places=2, default=40.0, help_text='Annual ROI percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='secondary_color',
            field=models.CharField(default='#FADBD8', help_text='Tenant secondary theme color in HEX format', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid hex code (e.g. #FF0000)', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('overdue', 'Overdue')], default='active', help_text='Tenant suspension status', max_length=10),
        ),
        migrations.AddField(
            model_name='tenant',
            name='unique_policy_prefix',
            field=models.CharField(default='APP', help_text='Prefix for unique policy numbers', max_length=10),
        ),
        migrations.AlterField(
            model_name='domain',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='core.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'module', 'tenant')},
        ),
        migrations.AlterModelTable(
            name='tenant',
            table='core_tenant',
        ),
        migrations.AlterModelTable(
            name='usernameindex',
            table='public_usernameindex',
        ),
        migrations.CreateModel(
            name='GlobalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_user', models.CharField(blank=True, help_text='Super-admin user ID from public tenant', max_length=36, null=True)),
                ('action', models.CharField(choices=[('platform_user_created', 'Platform User Created'), ('platform_user_updated', 'Platform User Updated'), ('platform_user_deleted', 'Platform User Deleted'), ('tenant_created', 'Tenant Created'), ('tenant_updated', 'Tenant Updated'), ('tenant_deleted', 'Tenant Deleted'), ('tenant_suspended', 'Tenant Suspended'), ('tenant_activated', 'Tenant Activated'), ('global_keypair_generated', 'Global Keypair Generated'), ('system_backup_created', 'System Backup Created'), ('audit_export_requested', 'Audit Export Requested'), ('tenant_quota_exceeded', 'Tenant Quota Exceeded'), ('global_login_failed', 'Global Login Failed'), ('security_alert_triggered', 'Security Alert Triggered')], max_length=50)),
                ('performed_by', models.CharField(blank=True, help_text='User ID who performed the action', max_length=36, null=True)),
                ('global_correlation_id', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('success', models.BooleanField(help_text='Indicates if the action was successful.', null=True)),
                ('affected_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_activities', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Global Activity',
                'verbose_name_plural': 'Global Activities',
                'db_table': 'core_globalactivity',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['affected_tenant', 'timestamp'], name='core_global_affecte_39b309_idx'), models.Index(fields=['affected_tenant', 'action', 'timestamp'], name='core_global_affecte_f0f7f0_idx'), models.Index(fields=['global_user', 'timestamp'], name='core_global_global__5b573a_idx'), models.Index(fields=['performed_by', 'timestamp'], name='core_global_perform_7cd440_idx'), models.Index(fields=['success', 'timestamp'], name='core_global_success_715c92_idx'), models.Index(fields=['timestamp'], name='core_global_timesta_1573cc_idx'), models.Index(fields=['global_correlation_id'], name='core_global_global__168f55_idx')],
            },
        ),
    ]
