# Generated by Django 5.2.5 on 2025-11-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('overdue', 'Overdue')], default='active', help_text='Tenant suspension status', max_length=10),
        ),
    ]
