# Generated by Django 5.2.2 on 2025-07-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tenant_about_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantconfig',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
