# Generated by Django 5.2.2 on 2025-07-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_tenantconfig_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
