# Generated by Django 5.2.5 on 2025-09-01 07:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tenant_logo_tenant_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('public_key', models.TextField()),
                ('private_key', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rsa_keys', to='core.tenant')),
            ],
        ),
    ]
