# Generated by Django 5.2.5 on 2025-09-02 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tenantkey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TenantKey',
        ),
    ]
