# Generated by Django 5.2.5 on 2025-11-11 21:23

import django.db.models.deletion
import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(default=tasks.models.gen_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('assigned_to_id', models.CharField(max_length=128)),
                ('assigned_to_first_name', models.CharField(blank=True, max_length=150)),
                ('assigned_to_last_name', models.CharField(blank=True, max_length=150)),
                ('assigned_to_email', models.EmailField(blank=True, max_length=254)),
                ('assigned_by_id', models.CharField(max_length=128)),
                ('assigned_by_first_name', models.CharField(blank=True, max_length=150)),
                ('assigned_by_last_name', models.CharField(blank=True, max_length=150)),
                ('assigned_by_email', models.EmailField(blank=True, max_length=254)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='not_started', max_length=20)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.CharField(default=tasks.models.gen_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('updated_by_id', models.CharField(max_length=128)),
                ('updated_by_first_name', models.CharField(max_length=150)),
                ('updated_by_last_name', models.CharField(max_length=150)),
                ('updated_by_email', models.EmailField(max_length=254)),
                ('completed_description', models.TextField(blank=True)),
                ('remaining_description', models.TextField(blank=True)),
                ('reason_for_incompletion', models.TextField(blank=True)),
                ('next_action_plan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='in_progress', max_length=20)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='tasks.task')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(default=tasks.models.gen_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=128)),
                ('user_first_name', models.CharField(max_length=150)),
                ('user_last_name', models.CharField(max_length=150)),
                ('user_email', models.EmailField(max_length=254)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
