# Generated by Django 5.2.5 on 2025-11-13 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_id_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_to_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
