# Generated by Django 5.2.5 on 2025-11-26 07:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('meeting_link', models.URLField(blank=True, help_text='Optional link for virtual meetings (Zoom, Teams, Google Meet, etc.)', max_length=500, null=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('specific_users', 'Specific Users')], default='private', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated_by_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-start_datetime'],
            },
        ),
    ]
