# Generated by Django 5.2.5 on 2025-11-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Optional link for virtual meetings (Zoom, Teams, Google Meet, etc.)', max_length=500, null=True),
        ),
    ]
