# Generated by Django 5.2.5 on 2025-11-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='include_all_tenant_users',
            field=models.BooleanField(default=False, help_text='If true, all tenant users are automatically added as participants'),
        ),
    ]
