version: '3.8'

services:
  messaging-db:
    image: postgres:15-alpine
    container_name: messaging_postgres
    environment:
      POSTGRES_DB: messaging_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - messaging_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - messaging_network

  redis:
    image: redis:7-alpine
    container_name: messaging_redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - messaging_network

  websocket:
    build: .
    container_name: messaging_websocket
    ports:
      - "3500:3000"
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      messaging-db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - messaging_network

networks:
  messaging_network:
    driver: bridge
  auth_service_default:
    external: true

volumes:
  messaging_postgres_data:
  redis_data: