# Generated by Django 5.2.2 on 2025-08-26 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('interview_start_date_time', models.DateTimeField()),
                ('interview_end_date_time', models.DateTimeField(blank=True, null=True)),
                ('meeting_mode', models.CharField(choices=[('Virtual', 'Virtual'), ('Physical', 'Physical')], max_length=20)),
                ('meeting_link', models.URLField(blank=True, max_length=255, null=True)),
                ('interview_address', models.TextField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('timezone', models.CharField(choices=[('UTC', 'UTC'), ('America/New_York', 'Eastern Time (US)'), ('America/Chicago', 'Central Time (US)'), ('America/Los_Angeles', 'Pacific Time (US)'), ('Europe/London', 'London'), ('Asia/Tokyo', 'Tokyo')], default='UTC', max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'job_applications_schedule',
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('qualification', models.TextField(max_length=255)),
                ('experience', models.TextField(max_length=255)),
                ('knowledge_skill', models.TextField(blank=True, null=True)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('resume_status', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='new', max_length=20)),
                ('screening_status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('screening_score', models.FloatField(blank=True, null=True)),
                ('employment_gaps', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(blank=True, default='Website', max_length=50, null=True)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('compliance_status', models.JSONField(blank=True, default=list)),
                ('interview_location', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_applications', to='core.branch')),
            ],
            options={
                'db_table': 'job_applications_job_application',
            },
        ),
    ]
