# Generated by Django 5.2.2 on 2025-08-26 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('job_application', '0001_initial'),
        ('talent_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='job_requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='talent_engine.jobrequisition'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='core.branch'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='job_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='job_application.jobapplication'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('tenant', 'job_requisition', 'email', 'branch')},
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('status', 'scheduled')), fields=('job_application',), name='unique_active_schedule_per_application'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('tenant', 'job_application', 'interview_start_date_time', 'branch')},
        ),
    ]
