# Generated by Django 5.2.5 on 2025-10-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='job_role',
            field=models.CharField(blank=True, default='user', max_length=255, null=True),
        ),
    ]
