# Generated by Django 5.2.5 on 2026-01-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentdetail',
            name='working_days',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
