# Generated by Django 5.2.5 on 2025-12-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='manage_permission',
            field=models.BooleanField(default=False),
        ),
    ]
