# Generated by Django 5.2.5 on 2025-10-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Right_to_rent_file',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='right_to_work/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Right_to_rent_file_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
