# Generated by Django 5.2.5 on 2025-09-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='next_of_kin_town',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
