# Generated by Django 5.2.5 on 2025-08-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='document_expiry_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='document_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='government_id_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='image_file',
        ),
        migrations.AddField(
            model_name='customuser',
            name='has_accepted_terms',
            field=models.BooleanField(default=False, help_text='Indicates if the user has accepted the terms and conditions.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image/'),
        ),
    ]
