# Generated by Django 5.2.5 on 2025-10-04 14:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_job_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('root-admin', 'Root-Admin'), ('co-admin', 'Co-Admin'), ('hr', 'HR'), ('staff', 'Staff'), ('user', 'User'), ('carer', 'Carer'), ('client', 'Client'), ('family', 'Family'), ('auditor', 'Auditor'), ('tutor', 'Tutor'), ('assessor', 'Assessor'), ('iqa', 'IQA'), ('eqa', 'EQA'), ('recruiter', 'Recruiter'), ('team_manager', 'Team Manager')], default='carer', max_length=20),
        ),
        migrations.AlterField(
            model_name='employmentdetail',
            name='employment_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employmentdetail',
            name='employment_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employmentdetail',
            name='probation_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employmentdetail',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
