# Generated by Django 5.2.5 on 2025-11-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_document_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='tenant_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
