# Generated by Django 5.2.5 on 2025-11-06 15:56

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_two_factor_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(help_text='Name of the skill', max_length=255)),
                ('proficiency_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], help_text='Level of proficiency in this skill', max_length=20, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the skill and experience')),
                ('acquired_date', models.DateField(blank=True, help_text='When the skill was acquired', null=True)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, help_text='Years of experience with this skill', null=True)),
                ('certificate', models.FileField(blank=True, help_text='Certificate or document proving this skill', max_length=255, null=True, upload_to='skill-certificates/', validators=[users.models.validate_image_or_pdf])),
                ('certificate_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_details', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Skill Detail',
                'verbose_name_plural': 'Skill Details',
                'unique_together': {('user_profile', 'skill_name')},
            },
        ),
    ]
