# Generated by Django 5.2.5 on 2025-12-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_employmentdetail_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_otp_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], default='email', help_text="User's preferred method for receiving OTP codes", max_length=10),
        ),
    ]
