# Generated by Django 5.2.5 on 2025-09-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otheruserdocuments_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otheruserdocuments',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
