# Generated by Django 5.2.5 on 2025-10-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_right_to_rent_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentdetail',
            name='salary_rate',
            field=models.CharField(blank=True, choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('bi_weekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('annual', 'Annual')], help_text='How often the user wants to be paid', max_length=20, null=True),
        ),
    ]
