# Generated by Django 5.2.5 on 2025-09-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_documentversion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='next_of_kin_name',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='address_line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='alt_contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='co_residents',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='communication_preference',
            field=models.CharField(choices=[('phone_call', 'Phone Call'), ('sms', 'SMS'), ('email', 'Email')], default='phone_call', max_length=20),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='gender_identity',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-Binary', 'Non-Binary'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='key_safe_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='lives_alone',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='next_of_kin_alt_contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='next_of_kin_contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='next_of_kin_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='next_of_kin_town',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='nhis_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='preferred_pronouns',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='primary_contact_email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='primary_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='primary_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='secondary_contact_email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='secondary_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='secondary_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Dr', 'Dr')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='type_of_residence',
            field=models.CharField(choices=[('private_home', 'Private Home'), ('care_home', 'Care Home'), ('assisted_living', 'Assisted Living'), ('sheltered', 'Sheltered Housing')], default='private_home', max_length=50),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
