# Generated by Django 5.2.5 on 2025-10-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivingriskassessment',
            name='supporting_document',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceverification',
            name='document',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='legalworkeligibility',
            name='document',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='otheruserdocuments',
            name='file',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='professionalqualification',
            name='image_file',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='proofofaddress',
            name='document',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='proofofaddress',
            name='nin_document',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Right_to_Work_share_code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
