# Generated by Django 5.2.5 on 2025-10-08 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_employmentdetail_salary_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='last_updated_by_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='availability',
            field=models.JSONField(blank=True, default=dict, help_text='Weekly availability schedule as JSON object', null=True),
        ),
        migrations.CreateModel(
            name='DocumentAcknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('tenant_id', models.CharField(max_length=255)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgments', to='users.document')),
            ],
            options={
                'indexes': [models.Index(fields=['document', 'tenant_id'], name='users_docum_documen_8e8b22_idx'), models.Index(fields=['user_id', 'tenant_id'], name='users_docum_user_id_9b3a85_idx')],
                'unique_together': {('document', 'user_id', 'tenant_id')},
            },
        ),
    ]
