# Generated by Django 5.2.5 on 2025-12-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_preferred_otp_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='next_of_kin_alternate_phone',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='next_of_kin_phone_number',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
