# Generated by Django 5.2.5 on 2025-11-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_document_tenant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='tenant_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
