# Generated by Django 5.2.5 on 2025-09-02 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_department_userprofile_dob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='modules',
        ),
    ]
