# Generated by Django 5.2.5 on 2025-10-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_drivingriskassessment_supporting_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivingriskassessment',
            name='supporting_document_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='certificate_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='insuranceverification',
            name='document_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='legalworkeligibility',
            name='document_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='otheruserdocuments',
            name='file_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='professionalqualification',
            name='image_file_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='proofofaddress',
            name='document_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='proofofaddress',
            name='nin_document_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='drivingriskassessment',
            name='supporting_document',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='driving_risk_docs/'),
        ),
        migrations.AlterField(
            model_name='insuranceverification',
            name='document',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='insurance_documents/'),
        ),
        migrations.AlterField(
            model_name='legalworkeligibility',
            name='document',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='legal_work_docs/'),
        ),
        migrations.AlterField(
            model_name='otheruserdocuments',
            name='file',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='other_user_documents'),
        ),
        migrations.AlterField(
            model_name='professionalqualification',
            name='image_file',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='professional_qualifications/'),
        ),
        migrations.AlterField(
            model_name='proofofaddress',
            name='document',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='proof_of_address/'),
        ),
        migrations.AlterField(
            model_name='proofofaddress',
            name='nin_document',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='nin_documents/'),
        ),
    ]
