# Generated by Django 5.2.5 on 2025-12-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_next_of_kin_alternate_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationdetail',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
