# Generated by Django 5.2.5 on 2025-10-08 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_document_last_updated_by_id_userprofile_availability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('permission_level', models.CharField(choices=[('view', 'View Only'), ('view_download', 'View and Download')], max_length=20)),
                ('tenant_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='users.document')),
            ],
            options={
                'indexes': [models.Index(fields=['document', 'tenant_id'], name='users_docum_documen_e30605_idx'), models.Index(fields=['user_id', 'tenant_id'], name='users_docum_user_id_305e67_idx')],
                'unique_together': {('document', 'user_id', 'tenant_id')},
            },
        ),
    ]
