# Generated by Django 5.2.5 on 2025-09-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_clientprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='next_of_kin_town',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='primary_contact_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='primary_contact_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='secondary_contact_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='secondary_contact_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
