# Generated by Django 5.2.5 on 2025-12-08 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0005_alter_educationdetail_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='InAppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('profile_update', 'Profile Update'), ('account_created', 'Account Created'), ('password_changed', 'Password Changed'), ('account_locked', 'Account Locked'), ('account_unlocked', 'Account Unlocked'), ('account_suspended', 'Account Suspended'), ('account_activated', 'Account Activated'), ('system_message', 'System Message')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_app_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'tenant', 'is_read', 'created_at'], name='users_inapp_user_id_5c1f09_idx'), models.Index(fields=['tenant', 'created_at'], name='users_inapp_tenant__f4a5ec_idx')],
            },
        ),
    ]
