# Generated by Django 5.2.5 on 2025-09-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userprofile_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Right_to_Work_file_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dbs_certificate_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dbs_update_file_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='drivers_licence_image1_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='drivers_licence_image2_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
