# Generated by Django 5.2.5 on 2025-10-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_document_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='Comma-separated tags (e.g., "tag1, tag2, tag3")', max_length=500),
        ),
    ]
