# Generated by Django 5.2.5 on 2025-09-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_right_to_work_file_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='drivers_licence_issuing_authority',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
