# Generated by Django 5.2.5 on 2025-10-30 16:06

import django.db.models.deletion
import django.utils.timezone
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_globaluser_tenant_account_name_tenant_account_number_and_more'),
        ('users', '0007_document_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roi_rate', models.CharField(blank=True, choices=[('on_demand', 'On Demand (Flexible)'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('bi_weekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual'), ('one_time', 'One-Time'), ('others', 'Others')], help_text="How often the user wants to receive ROI (set to 'On Demand' if flexible)", max_length=20, null=True)),
                ('custom_roi_rate', models.DecimalField(blank=True, decimal_places=2, help_text="Custom ROI rate value when roi_rate is 'on_demand'", max_digits=10, null=True)),
                ('investment_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('investment_start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated_by_id', models.CharField(blank=True, max_length=100, null=True)),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=0, help_text='Current available balance after withdrawals', max_digits=20)),
            ],
            options={
                'verbose_name': 'Investment Detail',
                'verbose_name_plural': 'Investment Details',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated_by_id', models.CharField(blank=True, max_length=100, null=True)),
                ('withdrawal_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('withdrawal_request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('withdrawal_approved_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('withdrawal_approved', models.BooleanField(default=False)),
                ('withdrawal_approved_by', models.JSONField(blank=True, help_text="JSON object with approver details: {'id': str, 'email': str, 'first_name': str, 'last_name': str, 'role': str}", null=True)),
                ('withdrawn_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('withdrawan', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Withdrawal Detail',
                'verbose_name_plural': 'Withdrawal Details',
            },
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ['-timestamp'], 'verbose_name': 'User Activity', 'verbose_name_plural': 'User Activities'},
        ),
        migrations.RemoveIndex(
            model_name='useractivity',
            name='users_usera_user_id_bd4c6e_idx',
        ),
        migrations.RemoveIndex(
            model_name='useractivity',
            name='users_usera_ip_addr_20d9f6_idx',
        ),
        migrations.RemoveField(
            model_name='proofofaddress',
            name='nin',
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='end_year_new',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='start_year_new',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='global_correlation_id',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='policy_number',
            field=models.CharField(blank=True, help_text='Auto-generated policy number for investors (e.g., PRO-000001)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='photo',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='client_photos/', validators=[users.models.validate_image_or_pdf]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super-admin', 'Super Admin'), ('admin', 'Admin'), ('root-admin', 'Root Admin'), ('co-admin', 'Co Admin'), ('hr', 'HR'), ('staff', 'Staff'), ('investor', 'Investor'), ('carer', 'Carer'), ('user', 'User'), ('client', 'Client'), ('family', 'Family'), ('auditor', 'Auditor'), ('tutor', 'Tutor'), ('assessor', 'Assessor'), ('iqa', 'IQA'), ('eqa', 'EQA'), ('recruiter', 'Recruiter'), ('team_manager', 'Team Manager')], default='carer', max_length=20),
        ),
        migrations.AlterField(
            model_name='drivingriskassessment',
            name='supporting_document',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='driving_risk_docs/', validators=[users.models.validate_image_or_pdf]),
        ),
        migrations.AlterField(
            model_name='educationdetail',
            name='certificate',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='Educational-certificates/', validators=[users.models.validate_image_or_pdf]),
        ),
        migrations.AlterField(
            model_name='educationdetail',
            name='end_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='educationdetail',
            name='start_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceverification',
            name='document',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='insurance_documents/', validators=[users.models.validate_image_or_pdf]),
        ),
        migrations.AlterField(
            model_name='legalworkeligibility',
            name='document',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='legal_work_docs/', validators=[users.models.validate_image_or_pdf]),
        ),
        migrations.AlterField(
            model_name='otheruserdocuments',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='other_user_documents', validators=[users.models.validate_image_or_pdf]),
        ),
        migrations.AlterField(
            model_name='professionalqualification',
            name='image_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='professional_qualifications/', validators=[users.models.validate_image_or_pdf]),
        ),
        migrations.AlterField(
            model_name='proofofaddress',
            name='document',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='proof_of_address/', validators=[users.models.validate_image_or_pdf]),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('password_reset_request', 'Password Reset Request'), ('password_reset_confirm', 'Password Reset Confirm'), ('account_lock', 'Account Lock'), ('account_unlock', 'Account Unlock'), ('account_suspend', 'Account Suspend'), ('account_activate', 'Account Activate'), ('ip_block', 'IP Block'), ('ip_unblock', 'IP Unblock'), ('impersonation', 'Impersonation'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('profile_updated', 'Profile Updated'), ('bulk_user_create', 'Bulk User Create'), ('user_password_regenerated', 'User Password Regenerated'), ('document_uploaded', 'Document Uploaded'), ('document_updated', 'Document Updated'), ('document_deleted', 'Document Deleted'), ('document_acknowledged', 'Document Acknowledged'), ('document_permission_granted', 'Document Permission Granted'), ('document_permission_revoked', 'Document Permission Revoked'), ('investment_created', 'Investment Created'), ('investment_updated', 'Investment Updated'), ('withdrawal_requested', 'Withdrawal Requested'), ('withdrawal_approved', 'Withdrawal Approved'), ('withdrawal_rejected', 'Withdrawal Rejected'), ('withdrawal_processed', 'Withdrawal Processed'), ('group_created', 'Group Created'), ('group_updated', 'Group Updated'), ('group_deleted', 'Group Deleted'), ('group_member_added', 'Group Member Added'), ('group_member_removed', 'Group Member Removed'), ('rsa_key_created', 'RSA Key Created'), ('terms_accepted', 'Terms Accepted'), ('session_clock_in', 'Session Clock In'), ('session_clock_out', 'Session Clock Out'), ('api_request', 'API Request'), ('export_requested', 'Export Requested'), ('bulk_operation', 'Bulk Operation'), ('tenant_user_created', 'Tenant User Created'), ('tenant_user_updated', 'Tenant User Updated'), ('tenant_user_deleted', 'Tenant User Deleted'), ('branch_created', 'Branch Created'), ('branch_updated', 'Branch Updated'), ('branch_deleted', 'Branch Deleted'), ('module_activated', 'Module Activated'), ('module_deactivated', 'Module Deactivated'), ('tenant_config_updated', 'Tenant Config Updated'), ('investment_withdrawn', 'Investment Withdrawn'), ('document_shared', 'Document Shared'), ('group_member_added', 'Group Member Added'), ('session_clocked_in', 'Session Clocked In'), ('session_clocked_out', 'Session Clocked Out')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Right_to_Work_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='right_to_work/', validators=[users.models.validate_image_or_pdf]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Right_to_rent_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='right_to_rent/', validators=[users.models.validate_image_or_pdf]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dbs_certificate',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='dbs_certificates/', validators=[users.models.validate_image_or_pdf]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dbs_update_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='dbs_update_service/', validators=[users.models.validate_image_or_pdf]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='drivers_licence_image1',
            field=models.FileField(blank=True, null=True, upload_to='driver_licences/', validators=[users.models.validate_image_or_pdf]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='drivers_licence_image2',
            field=models.FileField(blank=True, null=True, upload_to='driver_licences/', validators=[users.models.validate_image_or_pdf]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='profile_image/', validators=[users.models.validate_image_or_pdf]),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['tenant', 'timestamp'], name='users_usera_tenant__1c3652_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['tenant', 'action', 'timestamp'], name='users_usera_tenant__0bd4c2_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['tenant', 'user', 'timestamp'], name='users_usera_tenant__935672_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['tenant', 'performed_by', 'timestamp'], name='users_usera_tenant__4a5059_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['tenant', 'success', 'timestamp'], name='users_usera_tenant__3b91be_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['ip_address', 'timestamp'], name='users_usera_ip_addr_300c64_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['timestamp'], name='users_usera_timesta_6dbdeb_idx'),
        ),
        migrations.AddField(
            model_name='investmentdetail',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_details', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='withdrawaldetail',
            name='investment',
            field=models.ForeignKey(help_text='The investment this withdrawal is made against', on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='users.investmentdetail'),
        ),
        migrations.AddField(
            model_name='withdrawaldetail',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_details', to='users.userprofile'),
        ),
    ]
