# Generated by Django 5.2.5 on 2025-09-02 19:45

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_tenantkey'),
        ('users', '0007_alter_userprofile_drivers_licence_issuing_authority'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSAKeyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kid', models.CharField(default=users.models.generate_kid, max_length=64, unique=True)),
                ('private_key_pem', models.TextField()),
                ('public_key_pem', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsa_keys', to='core.tenant')),
            ],
        ),
    ]
