# Generated by Django 5.2.5 on 2025-09-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_blacklistedtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsakeypair',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
