# Generated by Django 5.2.5 on 2025-09-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rsakeypair_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='business_type',
            field=models.CharField(blank=True, help_text="Client's business type (e.g., supplier, customer, partner)", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='client_type',
            field=models.CharField(blank=True, help_text="Client's relationship with the company (e.g., direct customer)", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='communication_preferences',
            field=models.CharField(blank=True, help_text="Client's preferred communication channels (e.g., email, phone)", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='company_address',
            field=models.TextField(blank=True, help_text="Client company's physical address", null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='company_name',
            field=models.CharField(blank=True, help_text='Official name of the client company', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='complaints',
            field=models.JSONField(blank=True, help_text='Record of client complaints and resolutions', null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='contact_email',
            field=models.EmailField(blank=True, help_text="Contact person's email address", max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='contact_person_department',
            field=models.CharField(blank=True, help_text="Contact person's department", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='contact_person_name',
            field=models.CharField(blank=True, help_text="Primary contact person's full name", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='contact_person_title',
            field=models.CharField(blank=True, help_text="Contact person's job title", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='contact_phone',
            field=models.CharField(blank=True, help_text="Contact person's phone number", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Client's credit limit", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='credit_utilization',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Client's current credit usage", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='feedback',
            field=models.JSONField(blank=True, help_text='Client feedback and satisfaction ratings', null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='industry',
            field=models.CharField(blank=True, help_text="Client's industry or sector", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or comments about the client', null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='order_history',
            field=models.JSONField(blank=True, help_text='Record of past orders including dates, quantities, and values', null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='payment_history',
            field=models.JSONField(blank=True, help_text='Record of past payments including dates and amounts', null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='payment_terms',
            field=models.TextField(blank=True, help_text="Client's payment terms, methods, and schedules", null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='special_requirements',
            field=models.TextField(blank=True, help_text="Client's special requirements or requests (e.g., custom packaging)", null=True),
        ),
    ]
