# Generated by Django 5.2.5 on 2025-09-10 14:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_customuser_options_customuser_bio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockedIP',
        ),
        migrations.RemoveField(
            model_name='compliancereport',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='failedlogin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='user',
        ),
        migrations.DeleteModel(
            name='VulnerabilityAlert',
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='login_attempts',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='status',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='title',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='twitter_link',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.DeleteModel(
            name='ComplianceReport',
        ),
        migrations.DeleteModel(
            name='FailedLogin',
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
