import { PrismaClient, RequestUrgency } from '@prisma/client';
import { POSTCODES } from '../data/postcodes';
interface VisitTemplate {
    clientName: string;
    postcode: keyof typeof POSTCODES;
    hour: number;
    duration: number;
    urgency: RequestUrgency;
    requirements: string;
    notes: string;
    isDoubleHanded?: boolean;
}
export declare function createVisit(prisma: PrismaClient, template: VisitTemplate): Promise<{
    id: string;
    latitude: number | null;
    longitude: number | null;
    notes: string | null;
    approvedBy: string | null;
    approvedAt: Date | null;
    tenantId: string;
    status: import(".prisma/client").$Enums.RequestStatus;
    createdAt: Date;
    updatedAt: Date;
    subject: string;
    content: string;
    requestorEmail: string;
    requestorName: string | null;
    requestorPhone: string | null;
    address: string;
    postcode: string;
    urgency: import(".prisma/client").$Enums.RequestUrgency;
    requirements: string | null;
    estimatedDuration: number | null;
    scheduledStartTime: Date | null;
    scheduledEndTime: Date | null;
    emailMessageId: string | null;
    emailThreadId: string | null;
    sendToRostering: boolean;
    clusterId: string | null;
    processedAt: Date | null;
}>;
export declare function seedVisits(prisma: PrismaClient): Promise<{
    id: string;
    latitude: number | null;
    longitude: number | null;
    notes: string | null;
    approvedBy: string | null;
    approvedAt: Date | null;
    tenantId: string;
    status: import(".prisma/client").$Enums.RequestStatus;
    createdAt: Date;
    updatedAt: Date;
    subject: string;
    content: string;
    requestorEmail: string;
    requestorName: string | null;
    requestorPhone: string | null;
    address: string;
    postcode: string;
    urgency: import(".prisma/client").$Enums.RequestUrgency;
    requirements: string | null;
    estimatedDuration: number | null;
    scheduledStartTime: Date | null;
    scheduledEndTime: Date | null;
    emailMessageId: string | null;
    emailThreadId: string | null;
    sendToRostering: boolean;
    clusterId: string | null;
    processedAt: Date | null;
}[]>;
export {};
//# sourceMappingURL=visitFactory.d.ts.map