# Generated by Django 5.2.2 on 2025-08-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups that can access this forum', related_name='forums', to='groups.group'),
        ),
    ]
