# Generated by Django 5.2.2 on 2025-08-12 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chatmessage',
            table='ai_chat_chatmessage',
        ),
        migrations.AlterModelTable(
            name='chatsession',
            table='ai_chat_chatsession',
        ),
    ]
