# Generated by Django 5.2.5 on 2025-11-18 14:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0002_alter_document_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('unique_policy_id', models.CharField(max_length=50, unique=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('roi_rate', models.DecimalField(decimal_places=2, default=40.0, max_digits=5)),
                ('roi_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('on_demand', 'On Demand')], default='monthly', max_length=20)),
                ('roi_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('maturity_date', models.DateTimeField(blank=True, null=True)),
                ('last_roi_calculation', models.DateTimeField(blank=True, null=True)),
                ('next_roi_date', models.DateTimeField(blank=True, null=True)),
                ('min_withdrawal_months', models.PositiveIntegerField(default=4)),
                ('allow_partial_withdrawals', models.BooleanField(default=True)),
                ('auto_rollover', models.BooleanField(default=False)),
                ('rollover_option', models.CharField(choices=[('principal_only', 'Principal Only'), ('principal_plus_roi', 'Principal + ROI'), ('custom', 'Custom Amount')], default='principal_only', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('matured', 'Matured'), ('closed', 'Closed'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_policies', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='users.userprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'investments_policy',
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('unique_reference', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('entry_type', models.CharField(choices=[('deposit', 'Deposit'), ('top_up', 'Top Up'), ('withdrawal_principal', 'Withdrawal - Principal'), ('withdrawal_roi', 'Withdrawal - ROI'), ('roi_accrual', 'ROI Accrual'), ('fee', 'Fee'), ('adjustment', 'Adjustment')], max_length=25)),
                ('inflow', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('outflow', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('principal_balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('roi_balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='investments.investmentpolicy')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'investments_ledger',
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='ROIAccrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accrual_date', models.DateTimeField()),
                ('calculation_period', models.CharField(max_length=50)),
                ('principal_for_calculation', models.DecimalField(decimal_places=2, max_digits=20)),
                ('roi_rate_applied', models.DecimalField(decimal_places=2, max_digits=5)),
                ('roi_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_accrued', models.BooleanField(default=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roi_accruals', to='investments.investmentpolicy')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'investments_roi_accrual',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('withdrawal_type', models.CharField(choices=[('roi_only', 'ROI Only'), ('principal_only', 'Principal Only'), ('composite', 'Composite (Principal + ROI)')], max_length=20)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processed', 'Processed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('disbursement_bank', models.CharField(blank=True, max_length=255)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='investments.investmentpolicy')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'investments_withdrawal_request',
            },
        ),
        migrations.AddIndex(
            model_name='investmentpolicy',
            index=models.Index(fields=['tenant', 'policy_number'], name='investments_tenant__3625b5_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentpolicy',
            index=models.Index(fields=['user', 'status'], name='investments_user_id_c3f049_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentpolicy',
            index=models.Index(fields=['status', 'next_roi_date'], name='investments_status_5a2bdd_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['policy', 'entry_date'], name='investments_policy__f4546d_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['tenant', 'entry_date'], name='investments_tenant__273078_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['entry_type', 'entry_date'], name='investments_entry_t_eefd1a_idx'),
        ),
        migrations.AddIndex(
            model_name='roiaccrual',
            index=models.Index(fields=['policy', 'accrual_date'], name='investments_policy__95c036_idx'),
        ),
        migrations.AddIndex(
            model_name='roiaccrual',
            index=models.Index(fields=['is_paid', 'accrual_date'], name='investments_is_paid_c3720c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roiaccrual',
            unique_together={('policy', 'calculation_period')},
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['policy', 'status'], name='investments_policy__e104ac_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['user', 'request_date'], name='investments_user_id_359f93_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['status', 'request_date'], name='investments_status_916693_idx'),
        ),
    ]
