# Generated by Django 5.2.5 on 2025-11-20 09:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('investments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(choices=[('wht_dividends', 'WHT - Dividends'), ('wht_interest', 'WHT - Interest/ROI'), ('wht_rent', 'WHT - Rent'), ('wht_commission', 'WHT - Commission'), ('wht_professional', 'WHT - Professional Services'), ('wht_contracts', 'WHT - Contracts'), ('pit', 'Personal Income Tax'), ('cgt', 'Capital Gains Tax'), ('vat', 'Value Added Tax'), ('tet', 'Tertiary Education Tax'), ('company_tax', 'Company Income Tax')], max_length=30)),
                ('tax_period', models.CharField(help_text='Tax year/period (e.g., 2024, Q1-2024)', max_length=20)),
                ('calculation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='Amount before tax', max_digits=20)),
                ('tax_rate', models.DecimalField(decimal_places=4, help_text='Tax rate applied (e.g., 0.1000 for 10%)', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, help_text='Calculated tax amount', max_digits=20)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Amount after tax', max_digits=20)),
                ('taxable_income_bracket', models.CharField(blank=True, help_text="PIT bracket (e.g., '₦300,001 - ₦600,000')", max_length=50)),
                ('annual_income_total', models.DecimalField(blank=True, decimal_places=2, help_text='Total annual income for PIT calculations', max_digits=20, null=True)),
                ('status', models.CharField(choices=[('calculated', 'Calculated'), ('paid', 'Paid'), ('adjusted', 'Adjusted'), ('disputed', 'Disputed')], default='calculated', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Bank/payment reference for tax payment', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('firs_reference', models.CharField(blank=True, help_text='FIRS reference number', max_length=50)),
                ('tax_certificate_issued', models.BooleanField(default=False)),
                ('certificate_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_taxes', to=settings.AUTH_USER_MODEL)),
                ('calculated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculated_taxes', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_records', to='investments.investmentpolicy')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_records', to='investments.ledgerentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_records', to=settings.AUTH_USER_MODEL)),
                ('withdrawal_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_records', to='investments.withdrawalrequest')),
            ],
            options={
                'db_table': 'investments_tax_record',
                'ordering': ['-calculation_date'],
            },
        ),
        migrations.CreateModel(
            name='TaxCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('certificate_type', models.CharField(choices=[('wht', 'Withholding Tax Certificate'), ('pit', 'Personal Income Tax Certificate'), ('annual_summary', 'Annual Tax Summary'), ('cgt', 'Capital Gains Tax Certificate')], max_length=20)),
                ('tax_year', models.CharField(help_text='Tax year (e.g., 2024)', max_length=10)),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('validity_period_start', models.DateField()),
                ('validity_period_end', models.DateField()),
                ('total_gross_income', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_tax_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_tax_paid', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('net_income_after_tax', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('tax_breakdown', models.JSONField(default=dict, help_text='Detailed tax breakdown by type')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('revoked', 'Revoked'), ('reissued', 'Reissued')], default='draft', max_length=20)),
                ('digital_signature', models.TextField(blank=True, help_text='Digital signature for authenticity')),
                ('qr_code_data', models.TextField(blank=True, help_text='QR code data for verification')),
                ('firs_submission_date', models.DateTimeField(blank=True, null=True)),
                ('firs_reference', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_certificates', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_certificates', to=settings.AUTH_USER_MODEL)),
                ('related_tax_records', models.ManyToManyField(blank=True, related_name='certificates', to='investments.taxrecord')),
            ],
            options={
                'db_table': 'investments_tax_certificate',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='TaxSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wht_dividend_rate', models.DecimalField(decimal_places=4, default=0.1, help_text='10% default', max_digits=5)),
                ('wht_interest_rate', models.DecimalField(decimal_places=4, default=0.1, help_text='10% default', max_digits=5)),
                ('wht_rent_rate', models.DecimalField(decimal_places=4, default=0.1, help_text='10% default', max_digits=5)),
                ('wht_commission_rate', models.DecimalField(decimal_places=4, default=0.05, help_text='5% default', max_digits=5)),
                ('wht_professional_rate', models.DecimalField(decimal_places=4, default=0.05, help_text='5% default', max_digits=5)),
                ('wht_contract_rate', models.DecimalField(decimal_places=4, default=0.025, help_text='2.5% default', max_digits=5)),
                ('cgt_rate', models.DecimalField(decimal_places=4, default=0.1, help_text='10% default', max_digits=5)),
                ('vat_rate', models.DecimalField(decimal_places=4, default=0.075, help_text='7.5% default', max_digits=5)),
                ('tet_rate', models.DecimalField(decimal_places=4, default=0.025, help_text='2.5% default', max_digits=5)),
                ('small_company_threshold', models.DecimalField(decimal_places=2, default=25000000.0, help_text='₦25M threshold', max_digits=20)),
                ('small_company_rate', models.DecimalField(decimal_places=4, default=0.2, help_text='20% rate', max_digits=5)),
                ('standard_company_rate', models.DecimalField(decimal_places=4, default=0.3, help_text='30% rate', max_digits=5)),
                ('auto_calculate_taxes', models.BooleanField(default=True)),
                ('require_tax_certificates', models.BooleanField(default=True)),
                ('firs_integration_enabled', models.BooleanField(default=False)),
                ('tax_year_start_month', models.PositiveIntegerField(default=1, help_text='1=January, 4=April, etc.')),
                ('notify_tax_calculations', models.BooleanField(default=True)),
                ('notify_certificate_issuance', models.BooleanField(default=True)),
                ('tax_reminder_days', models.PositiveIntegerField(default=30, help_text='Days before tax deadline to send reminders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_settings', to='core.tenant')),
            ],
            options={
                'db_table': 'investments_tax_settings',
            },
        ),
        migrations.AddIndex(
            model_name='taxrecord',
            index=models.Index(fields=['tenant', 'tax_type', 'tax_period'], name='investments_tenant__896324_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrecord',
            index=models.Index(fields=['user', 'tax_period'], name='investments_user_id_332aac_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrecord',
            index=models.Index(fields=['policy', 'calculation_date'], name='investments_policy__6d8767_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrecord',
            index=models.Index(fields=['status', 'calculation_date'], name='investments_status_ff1391_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrecord',
            index=models.Index(fields=['tax_type', 'status'], name='investments_tax_typ_765c07_idx'),
        ),
        migrations.AddIndex(
            model_name='taxcertificate',
            index=models.Index(fields=['tenant', 'certificate_number'], name='investments_tenant__48b6b9_idx'),
        ),
        migrations.AddIndex(
            model_name='taxcertificate',
            index=models.Index(fields=['user', 'tax_year'], name='investments_user_id_1ccdf8_idx'),
        ),
        migrations.AddIndex(
            model_name='taxcertificate',
            index=models.Index(fields=['certificate_type', 'status'], name='investments_certifi_9a7a50_idx'),
        ),
        migrations.AddIndex(
            model_name='taxcertificate',
            index=models.Index(fields=['issue_date'], name='investments_issue_d_f3a695_idx'),
        ),
    ]
