# Generated by Django 5.2.5 on 2025-11-25 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('investments', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentpolicy',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investmentpolicy',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='investmentpolicy',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AddField(
            model_name='investmentpolicy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='investments.investmentpolicy'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AddField(
            model_name='roiaccrual',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roi_accruals', to='investments.investmentpolicy'),
        ),
        migrations.AddField(
            model_name='roiaccrual',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AddField(
            model_name='taxcertificate',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxcertificate',
            name='issued_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxcertificate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AddField(
            model_name='taxcertificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxrecord',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_taxes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxrecord',
            name='calculated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculated_taxes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxrecord',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_records', to='investments.investmentpolicy'),
        ),
        migrations.AddField(
            model_name='taxrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AddField(
            model_name='taxrecord',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_records', to='investments.ledgerentry'),
        ),
        migrations.AddField(
            model_name='taxrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxcertificate',
            name='related_tax_records',
            field=models.ManyToManyField(blank=True, related_name='certificates', to='investments.taxrecord'),
        ),
        migrations.AddField(
            model_name='taxsettings',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_settings', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_withdrawals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='investments.investmentpolicy'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxrecord',
            name='withdrawal_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_records', to='investments.withdrawalrequest'),
        ),
        migrations.AddIndex(
            model_name='investmentpolicy',
            index=models.Index(fields=['tenant', 'policy_number'], name='investments_tenant__3625b5_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentpolicy',
            index=models.Index(fields=['user', 'status'], name='investments_user_id_c3f049_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentpolicy',
            index=models.Index(fields=['status', 'next_roi_date'], name='investments_status_5a2bdd_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['policy', 'entry_date'], name='investments_policy__f4546d_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['tenant', 'entry_date'], name='investments_tenant__273078_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['entry_type', 'entry_date'], name='investments_entry_t_eefd1a_idx'),
        ),
        migrations.AddIndex(
            model_name='roiaccrual',
            index=models.Index(fields=['policy', 'accrual_date'], name='investments_policy__95c036_idx'),
        ),
        migrations.AddIndex(
            model_name='roiaccrual',
            index=models.Index(fields=['is_paid', 'accrual_date'], name='investments_is_paid_c3720c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roiaccrual',
            unique_together={('policy', 'calculation_period')},
        ),
        migrations.AddIndex(
            model_name='taxcertificate',
            index=models.Index(fields=['tenant', 'certificate_number'], name='investments_tenant__48b6b9_idx'),
        ),
        migrations.AddIndex(
            model_name='taxcertificate',
            index=models.Index(fields=['user', 'tax_year'], name='investments_user_id_1ccdf8_idx'),
        ),
        migrations.AddIndex(
            model_name='taxcertificate',
            index=models.Index(fields=['certificate_type', 'status'], name='investments_certifi_9a7a50_idx'),
        ),
        migrations.AddIndex(
            model_name='taxcertificate',
            index=models.Index(fields=['issue_date'], name='investments_issue_d_f3a695_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['policy', 'status'], name='investments_policy__e104ac_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['user', 'request_date'], name='investments_user_id_359f93_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['status', 'request_date'], name='investments_status_916693_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrecord',
            index=models.Index(fields=['tenant', 'tax_type', 'tax_period'], name='investments_tenant__896324_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrecord',
            index=models.Index(fields=['user', 'tax_period'], name='investments_user_id_332aac_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrecord',
            index=models.Index(fields=['policy', 'calculation_date'], name='investments_policy__6d8767_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrecord',
            index=models.Index(fields=['status', 'calculation_date'], name='investments_status_ff1391_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrecord',
            index=models.Index(fields=['tax_type', 'status'], name='investments_tax_typ_765c07_idx'),
        ),
    ]
